xiaoyifang/goldendict-ng

file.cc

Enhance the function to check whether the file exists, support large files

Enhance the function to check whether the file exists, support large files

---

articleview.cc
articleview.hh
mainwindow.cc
mutex.hh
scanpopup.cc

* on Macbook pro ,  scrolling from trackpad will trigger zoom in/out; goldendict/goldendict#1241
* fix a deadlock in mutex.hh
* make some sync function async

disable macOS trackpad zoom; fix a deadlock

---

.github/workflows/macos-6.2.yml
.github/workflows/macos.yml

make a beautiful dmg file for macOS.
my build result:
https://github.com/ngn999/goldendict/releases
#24

make macOS dmg file more beautiful

---

.github/workflows/macos-6.2.yml
.github/workflows/macos.yml

had check the log from github action.
fix #42

fix macOS package problem; it's a workaround, waiting for macdeploy fix

---

articleview.cc
articleview.hh
epwing_book.cc

fulltext changes may be conflict 
the epwing should be ok.

merge upstream changes

---

aard.cc
dsl.cc
mdictparser.hh
mdx.cc
slob.cc
zim.cc

`string( QObject::tr( "Article loading error" ).toUtf8().constData() )`
convert to 
`QString::toStdString`

opt: replace string() with QString::toStdstring

---

btreeidx.hh
ftshelpers.cc
ftshelpers.hh
mdx.cc
slob.cc
zim.cc

add fulltext CJK search concurrent.

concurrent create fulltext index

---

mainwindow.cc
mainwindow.hh
scanpopup.cc

fix:add log to clipboard datachange signal

fix:add log to clipboard datachange signal

---

aard.cc
bgl.cc
dictdfiles.cc
dictionary.cc
dictionary.hh
dsl.cc
epwing.cc
ftshelpers.cc
ftshelpers.hh
fulltextsearch.cc
fulltextsearch.hh
gls.cc
mainwindow.cc
mdx.cc
sdict.cc
slob.cc
stardict.cc
xdxf.cc
zim.cc

ignored:
[Full-text search: Use separate thread pool for search requests](https://github.com/xiaoyifang/goldendict/commit/e333a03d7cc28822a76f7fbea2c8a8158d64ecfb)
[Full-text search: Reduce max thread count](https://github.com/xiaoyifang/goldendict/commit/3b2df81b3d8372d2d19fb2481b4710a316dd93df)

merge upstream fixes

---

btreeidx.cc
btreeidx.hh
dictheadwords.cc
dictheadwords.hh
dictheadwords.ui
dictionary.hh
goldendict.pro
headwordslistmodel.cpp
headwordslistmodel.h

especially when the dictionary has a very large collecton of headword.

opt: improve headword dialog performance

---

config.cc
dsl_details.cc

contain the changes of dsl option tags m 
dsl warning log level

sync upstream 

---

preferences.cc
preferences.hh
preferences.ui

fix revert c5035d87fcc93  conflict

---

article_netmgr.cc
base/globalregex.cc
base/globalregex.hh
zim.cc

fix <meta http-equiv="Refresh"

fix: zim dictionary auto refresh logic

---

README.md

The structure is much cleaner now. No technical info was removed.

Marketing Overhaul README.md

---

.github/workflows/cmake build test.yml
.gitmodules
CMakeLists.txt

cmake:fix linux build

---

mainwindow.cc
mainwindow.hh

closes https://github.com/xiaoyifang/goldendict/issues/279
This is almost identical to the pervious one

refactor: remove duplicated favoriatePane shortcut setting

---

src/dict/lingualibre.cpp

* set timeout to 6s
* get rid of reply with errors
related https://github.com/xiaoyifang/goldendict/issues/282#issuecomment-1366154091

lingua: add safeguards to errors

---

mainwindow.cc

fix https://github.com/xiaoyifang/goldendict/pull/277#issuecomment-1366510230
just add 4 more lines to our bloated mainwindow.cc

fix: reload all pages when darkreader mode changes in perferences

---

src/dict/lingualibre.cpp

close https://github.com/xiaoyifang/goldendict/issues/294

lingua: add " " to <a href= >

---

mainwindow.cc

For detail, see the comments in the code.
fix https://github.com/xiaoyifang/goldendict/issues/300
fix https://github.com/goldendict/goldendict/issues/1356

fix: Unsatisfactory "Close To Tray" behavior on macOS

---

multimediaaudioplayer.cc
multimediaaudioplayer.hh

fix: always repeat the first played sound 

---

scanpopup.cc
scanpopup.hh

upstream:save/restore scanpopup position

---

mediawiki.cc

fix:wikipedia url request

---

article_maker.cc

This fixes most icons and images, but it is still affected by #363.
See prior discussion at https://github.com/darkreader/darkreader/issues/10530
CC @xiaoyifang and @Enonutting

Add DarkReader.setFetchMethod()

---

mainwindow.cc

fix https://github.com/xiaoyifang/goldendict/pull/366#issuecomment-1457445072

fix: move enableScanningAction code after scanPopup's initialization

---

.clang-format

BraceWrapping->AfterControlStatement:false
->BeforeCatch:true

made some clang-format changes

---

.github/workflows/macos-6.x.yml
.github/workflows/macos-homebrew-PR-check.yml
.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/windows-6.x-xapian.yml
.github/workflows/windows-6.x.yml

wish the ffmpeg issue in Windows has been fixed.

bump qt version to qt6.4.3

---

ankiconnector.cpp
ankiconnector.h
articleview.cc
articleview.hh
config.cc
config.hh
howto/how to connect with anki.md
mainwindow.cc
preferences.cc
preferences.ui
scanpopup.cc

This PR adds an ability to configure the "Word" and "Definition" fields. It is also possible to include the entire search string on a card as a "Sentence" field.
https://user-images.githubusercontent.com/69171671/224502179-27b89609-6bf4-488a-87bc-2fa918bad3f2.mp4

Improve Anki support

---

dictinfo.cc
dictinfo.ui

display dictionary description as html 
result:

feature:display dictionary description as html

---

article-style-st-babylon.css
article-style-st-lingvo.css
article-style-st-modern.css
article_maker.cc
articlewebview.cc
articlewebview.hh
src/ui/articleview.cpp

Reverts xiaoyifang/goldendict#393
https://github.com/xiaoyifang/goldendict/issues/357

Revert "fix white flash in dark reader mode"

---

sources.ui

fix: enable tabwidget scrollbuttons

---

ankiconnector.cpp
ankiconnector.h

* Fix the `application/json` typo
* Use  a raw string to create postTemplate
* Use a constant for timeout

Refactor Anki connector

---

mdx.cc

at rare conditions ,  the for loop will continue to run until the request is canceled.

fix: a possible bug

---

article_maker.cc
article_netmgr.cc
article_netmgr.hh
dictionary.cc
dictionary.hh

use nonblock datarequest

---

article_netmgr.cc
dictionary.cc
dictionary.hh

take the code from vedgy's webengine port

fix: cpu will rise when no data available

---

iframeschemehandler.cpp

users report:
on macos
this issue may has some connection with https://bugreports.qt.io/browse/QTBUG-112483
use a workaround to fix this .

fix: iframe encoding error on certain website dictionaries

---

main.cc

We will brainlessly obtain those feature automatically:
A `-h --help` to display what options are available:
```
Usage: ./goldendict [options] [word]
A dictionary lookup program.
Options:
-h, --help                               Displays help on commandline
options.
--help-all                               Displays help including Qt specific
options.
-l, --log-to-file                        Save debug messages to gd_log.txt in
the config folder.
-g, --group-name <groupName>             Change the group of main window.
-p, --popup-group-name <popupGroupName>  Change the group of popup.
Arguments:
word                                     Word or sentence to query.
```
Short form of options like `-g`.
More flexible format: `goldendict -g="groupname"` is equal to `-g groupname`.
Allow passing …

Replace custom commandline parser with QCommandLineParser

---

scanpopup.cc

this part of changes is from https://github.com/xiaoyifang/goldendict/pull/415#discussion_r1145639728

remove resize event code

---

src/ui/articleview.cpp

fix:favorite panel arrow up/down does not work

---

mainwindow.cc

fix: code smell

---

src/initializing.cc
src/initializing.hh
src/ui/mainwindow.cc

fix: remove unused windowsstyle.cc(.hh)

---

src/main.cc
src/ui/mainwindow.cc

* Skip command lines parsing when no args at all.
* Implement this https://github.com/goldendict/goldendict/pull/965
* 
```
-t, --toggle-scan-popup                  Toggle scan popup.
```

Implement `--toggle-scan-popup` command line option

---

src/article_maker.cc
src/stylesheets/article-style.css

This will make the display more comfortable
fix #536

opt: give a min-height to the last dictionary

---

src/article_maker.cc
src/stylesheets/article-style-darkmode.css
src/stylesheets/css.qrc

opt: when in darkmode ,make the current article more significant

---

src/dict/dictionary.cc
src/ui/groups.cc
src/ui/groups.hh
src/ui/groups.ui
src/ui/groups_widgets.cc
src/ui/groups_widgets.hh

Implement design 2: https://github.com/xiaoyifang/goldendict-ng/issues/483#issuecomment-1515866772
It turns out less than 30 lines of code are needed :sweat_smile: :sweat_smile:

Auto Grouping by Dict' Containning Folder

---

src/dict/dictionary.cc
src/dict/forvo.cc
src/headwordsmodel.cc
src/headwordsmodel.hh
src/ui/dictheadwords.cc
src/ui/dictheadwords.hh

the wildcard and regex filter does not work as expected.
fix #556

fix: headword dialog filter and export

---

src/headwordsmodel.cc
src/headwordsmodel.hh
src/ui/dictheadwords.cc

opt: use QTextStream to generate the BOM

---

src/ui/mainwindow.cc

opt:add a statusbar notification when finshed save article

---

src/common/globalbroadcaster.hh
src/ui/editdictionaries.cc
src/ui/favoritespanewidget.cc
src/ui/mainwindow.cc
src/ui/mainwindow.hh
src/ui/scanpopup.cc
src/ui/scanpopup.hh

this bug was existed for a long time
fix #569

fix: can not remove favorite word in popup

---

src/config.cc
src/config.hh
src/ui/mainwindow.cc
src/ui/preferences.cc

seperate the persistentstoragepath with cachepath

opt: use unified cache dir

---

README.md
website/docs/install.md

close https://github.com/xiaoyifang/goldendict-ng/issues/570

docs: update linux package links

---

.github/workflows/deploy_website.yml

Missed a star
Also add manual trigger

Fix deploy_website does not trigger

---

src/common/htmlescape.cc

fix: the implementation of unescapeutf8 is wrong

---

src/common/wildcard.cc

opt: replace wildcardtoregularexpression with qt builtin method

---

src/common/htmlescape.cc
src/common/htmlescape.hh
src/dict/dictdfiles.cc
src/dict/epwing_book.cc
src/dict/gls.cc
src/dict/stardict.cc

opt:refactor html:unescape method

---

src/ui/preferences.ui

opt: relayout the preference language controls

---

src/btreeidx.cc
src/btreeidx.hh
src/dict/aard.cc
src/dict/bgl.cc
src/dict/dictserver.cc
src/dict/dsl.cc
src/dict/epwing.cc
src/dict/gls.cc
src/dict/hunspell.cc
src/dict/mdx.cc
src/dict/sdict.cc
src/dict/slob.cc
src/dict/stardict.cc
src/dict/xdxf.cc
src/dict/zim.cc
src/ftshelpers.hh
src/wordfinder.cc

opt: replace qthreadpool with qfuture

---

src/ui/dictionarybar.hh
src/ui/mainwindow.cc

clean: use new Signal Slot syntax

---

README.md
website/docs/developer.md

close https://github.com/xiaoyifang/goldendict-ng/issues/619
Just move the "contributing" section up, after the `install` but before `build from source`

docs: update "contributing"

---

src/ui/scanpopup.cc
src/ui/scanpopup.ui

opt: enable pronounce button when audio is available

---

src/common/utils.cc
src/common/utils.hh
src/dict/mdx.cc

opt:refactor an implict string conversion to a purposeful name

---

goldendict.pro

pave way for further vcpkg refactor

fix: on Windows, link -lzlib instead of -lz

---

.github/scripts/windows-publish.ps1
.github/workflows/ubuntu-6.2-xapian.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/ubuntu-PR-check.yml
.github/workflows/windows-6.x-xapian.yml
README.md
goldendict.pro
src/main.cc
thirdparty/breakpad/Readme.md

fix #578 
currently only enable breakpad on  windows xapian version

feat: add breakpad crash support

---

src/main.cc
thirdparty/qtsingleapplication/src/qtlocalpeer.cpp

fix:use a different socketname

---

src/stylesheets/article-style-st-modern.css

Seems not in great need. 
only provide in modern style.

opt: make some space padding at left and right of articlebody

---

src/article_maker.cc
src/article_maker.hh
src/common/globalbroadcaster.hh
src/instances.cc
src/instances.hh
src/ui/articleview.cc
src/ui/articleview.hh
thirdparty/qtsingleapplication/src/qtsingleapplication.cpp
thirdparty/qtsingleapplication/src/qtsingleapplication.h

fix: the scanpopup found dictionaries mixed with mainwindows

---

src/main.cc

fix: enable font antialias

---

src/ui/scanflag.cc
src/ui/scanpopup.cc
src/ui/scanpopup.hh

taken the changes from From https://github.com/goldendict/goldendict/commit/83020389c802577075831f7b45cc1a4d3017c86f

fix: multi monitor issue

---

src/ui/articleview.hh
src/ui/articlewebview.cc
src/ui/articlewebview.hh
src/ui/mainwindow.cc

fix #660
still not found out why mainwindows got the focus while not webview.
use a workaround to fix this, expect to change in the future.

fix: press enter the article view does not get the focus

---

.github/workflows/auto clang format.yml
src/common/globalbroadcaster.hh
src/ui/articlewebpage.cc
src/ui/mainwindow.cc
src/ui/mainwindow.hh
src/ui/preferences.cc

This reverts commit e84b5aa8618809ceade06b557525bf84722f1725.
related with #680

Revert "feature:webengineprofile use non off record profile"

---

.github/workflows/auto clang format.yml
src/article_maker.cc
src/ui/articleview.cc
src/ui/mainwindow.cc

opt: let qt handle the language direction

---

src/dict/dictionary.cc

check whether the current path is dir already
fix #723

fix: open epwing dictionary folder

---

src/dict/aard.cc
src/dict/bgl.cc
src/dict/dictdfiles.cc
src/dict/dictionary.cc
src/dict/dictionary.hh
src/dict/dsl.cc
src/dict/epwing.cc
src/dict/gls.cc
src/dict/loaddictionaries.cc
src/dict/mdx.cc
src/dict/sdict.cc
src/dict/slob.cc
src/dict/stardict.cc
src/dict/xdxf.cc
src/dict/zim.cc
src/langcoder.hh
website/docs/custom_dictionary_name.md
website/mkdocs.yml

feat: allow to customize dictionary name

---

thirdparty/qtsingleapplication/src/qtlocalpeer.cpp

fix: qChecksum compile warning

---

.github/workflows/auto clang format.yml

add comment if the pr is from other person

action: auto clang format

---

src/ui/dictheadwords.cc
src/ui/dictheadwords.hh

fix: switch dictionary should change the headwords in the dialog

---

CMakeLists.txt
CMake_Unix.cmake
CMake_Win.cmake

fix: cmake install will install extra header files

---

src/stylesheets/article-style.css

opt: slob dictionary does not display goldendict headword

---

CMakeLists.txt

:sweat_smile: sorry, forget to delete a line
https://github.com/xiaoyifang/goldendict-ng/pull/787

cmake: duplicated tomlplusplus include

---

src/ui/preferences.cc
src/ui/preferences.hh

refactor the disabledType string build

fix: code smells

---

.github/workflows/ubuntu-6.2-xapian.yml
.github/workflows/ubuntu.yml

related: https://github.com/xiaoyifang/goldendict-ng/issues/795

action: add fcitx im module to AppImage builds

---

src/dict/bgl_babylon.cc
src/dict/bgl_babylon.hh

bgl_babylon.cc
fix #768
fix #770

fix: invalid data access of data field

---

.github/workflows/ubuntu-6.2-xapian.yml

add fcitx support to qt6 appimage build
https://github.com/xiaoyifang/goldendict-ng/issues/795

action: add fcitx5-qt6 im plugin to appimage build

---

src/ui/mainwindow.cc

fix: new release check ,download url is incorrect

---

src/dict/xdxf2html.cc

Fix https://github.com/xiaoyifang/goldendict-ng/issues/811
The problem is a mixture of wrong code in the original GD and Qt6's internal updates:
* XML should not use `&nbsp;`
* but in Qt5 and before, this is accepted at `QDomDocument::setContent`
* From Qt6, it will be rejected, thus failing to load correctly
---
This PR also updates deprecated API usage for Qt6.

Fix: stardict's xdxf resources failed to convert because Qt6's QDomDocument is stricter

---

src/common/utf8.cc
src/common/utf8.hh
src/dict/dsl_details.cc

fix: support dsl dictionary utf encoding detection

---

src/config.hh
src/main.cc
src/ui/mainwindow.cc
src/ui/scanpopup.cc

or start goldendict like
```
goldendict -r
```
the existed state will be ignored and reset when quit the application.

fix: add an --reset-windows-state option to command line

---

src/ui/mainwindow.cc
src/ui/translatebox.cc

A regression introduced in https://github.com/xiaoyifang/goldendict-ng/commit/967926cee45def1c5382b8c5be2d104e9bb18685

fix regression: select translation line text when got focused

---

src/fulltextsearch.cc
src/ui/articleview.cc
src/ui/favoritespanewidget.cc
src/ui/favoritespanewidget.hh
src/ui/historypanewidget.cc
src/ui/historypanewidget.hh
src/ui/orderandprops.cc
src/ui/orderandprops.hh

At most 2 more PR, and this is all finished :)

clean: convert a few trivial old SIGNAL/SLOT to new syntax

---

src/dict/sources.cc
src/dict/sources.hh
src/fulltextsearch.hh
src/ui/mainwindow.cc

fix: qtimer release memory

---

.github/workflows/macos-homebrew-xapian.yml
.github/workflows/ubuntu-6.2-xapian.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-6.x-xapian.yml
.github/workflows/windows.yml
src/config.cc

clean: remove config old code

---

goldendict.pro
src/main.cc
src/ui/about.cc
src/version.cc
src/version.hh

close https://github.com/xiaoyifang/goldendict-ng/issues/867

feat: add -v --version flag to CLI

---

src/dict/zim.cc

close https://github.com/xiaoyifang/goldendict-ng/issues/872

feat: load and display ZIM dictionary icon

---

.github/workflows/ubuntu-6.2-xapian.yml
.github/workflows/ubuntu.yml

ubuntu: appimage use ubuntu 20.04 instead

---

.github/workflows/macos-homebrew-nobreakpad.yml
goldendict.pro
src/dict/dictionary.cc
src/dict/sources.hh
src/fulltextsearch.hh
src/main.cc
src/speechclient.cc
src/speechclient.hh
src/ui/editdictionaries.cc
src/ui/editdictionaries.hh
src/ui/groups.cc
src/ui/groups_widgets.cc
src/ui/groups_widgets.hh

relate #854 
should not make things worse.
fixed some issues found during the exploration on Maco13 crash issue.

fix: refactor editDictionary logic

---

src/langcoder.cc

fix:dsl language parse issue

---

src/dict/dictdfiles.cc
src/dict/programs.cc
src/dict/sounddir.cc
src/dict/voiceengines.cc
src/dict/website.cc
src/dict/zipsounds.cc

https://github.com/xiaoyifang/goldendict-ng/issues/890

clean: unify how data added to dataRequestInstant

---

src/speechclient.cc
src/speechclient.hh

too many locale tts initialization cost too much time.

fix: tts only enable current locale

---

goldendict.pro
src/dict/dsl.cc

sync changes in commit  https://github.com/goldendict/goldendict/commit/a2be1797498a604634413c72739eb2f82aef00a2

opt: dsl target url attribute 

---

locale/crowdin.ts
src/config.cc
src/config.hh
src/ftshelpers.cc
src/ui/articleview.cc
src/ui/preferences.cc
src/ui/preferences.ui

opt: add fullindex position

---

src/btreeidx.cc
src/common/folding.cc
src/common/folding.hh
src/dict/stardict.cc
src/ftshelpers.cc

fix #928
This is a workaround.

fix: when search hypen `-` alone will result too much unnecessary result.

---

src/iframeschemehandler.cc

fix: website encoding problem

---

src/iframeschemehandler.cc

fix: qt5 website output response as text/plain

---

src/speechclient.cc
src/termination.cc

fix: terminator handler does not work as expected

---

src/ui/mainwindow.cc

fix: a possible crash of restoreState() in linux with qt6.5.1

---

.github/workflows/macos-homebrew-breakpad.yml
.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-6.x.yml
.github/workflows/windows.yml

when package a release version , the commit log will be too much

action: remove commit log changes

---

src/dict/slob.cc

and reduce the impact to normal query when create slob fulltext index

opt: boost slob fulltext speed

---

src/dict/slob.cc
src/ui/dictinfo.cc
src/ui/dictinfo.hh
src/ui/dictinfo.ui

opt: add open index folder to dict info dialog

---

src/ui/articleview.cc
src/ui/articleview.hh
src/ui/mainwindow.cc

https://github.com/xiaoyifang/goldendict-ng/assets/105986/b483ef5c-dcdc-420e-a2ce-1c6374dff9fe
pay attention to the group widget
fix #531

feat: sync group widget with tab (one group per tab)

---

src/article_maker.cc
src/audiolink.cc
src/pronounceengine.cc
src/pronounceengine.hh

fix: pronounce the first dictionary audio if availabe

---

src/dict/dictionary.hh
src/ui/groups_widgets.cc

fix https://github.com/xiaoyifang/goldendict-ng/issues/886
Just ignore them :sweat_smile:

fix: website/program should not appears in "AutoGroupByFolder"

---

src/ui/mainwindow.cc
src/ui/scanpopup.cc

fix: sound played twice in popup dialog

---

src/decompress.cc
src/decompress.hh
src/dict/epwing.cc
src/dict/epwing_book.cc
src/dict/epwing_charmap.cc
src/dict/loaddictionaries.cc
src/dict/slob.cc
src/dict/slob.hh
src/ui/preferences.cc
website/docs/howto/build_from_source.md

* slob should not depends on MAKE_ZIM_SUPPORT
* cmake failed to build when WITH_EPWING disabled.
close https://github.com/xiaoyifang/goldendict-ng/issues/953

fix: a few build problems about zim/slob ,epwing

---

CMakeLists.txt
redist/io.github.xiayifang.goldendict_ng.metainfo.xml
redist/org.xiaoyifang.GoldenDict_NG.desktop

https://github.com/flathub/flathub/pull/4353
* Change metadata.xml's id to `io.github.xiayifang.goldendict_ng`
* add `<releases>`, which contains the history of releases.
Don't merge yet until all requirements are fulfilled.

Changes required by Flatpak

---

locale/crowdin.ts
website/docs/howto/how to update crowdin.ts file.md

I18n: update ts

---

src/ui/articleview.cc
src/ui/mainwindow.cc

fix: shortcut navigation through dictionary and page

---

src/config.cc
src/config.hh
src/ui/mainwindow.cc

fix #1004 
this is a workaround solution.

fix: restore maximize geometry

---

src/dict/aard.cc
src/dict/bgl.cc
src/dict/dictdfiles.cc
src/dict/dsl.cc
src/dict/epwing.cc
src/dict/gls.cc
src/dict/mdx.cc
src/dict/sdict.cc
src/dict/slob.cc
src/dict/stardict.cc
src/dict/xdxf.cc
src/dict/zim.cc

opt: remove unnecessary code

---

src/config.cc
src/config.hh
src/ui/mainwindow.cc

Reverts xiaoyifang/goldendict-ng#1013

Revert "fix: restore maximize geometry"

---

src/ui/mainwindow.cc

https://bugreports.qt.io/browse/QTBUG-115074
close https://github.com/xiaoyifang/goldendict-ng/issues/1016

fix: Qt6.4/5's maximum bug https://bugreports.qt.io/browse/QTBUG-115074

---

src/dict/zipsounds.cc

fix: sonar warning about uninitialized variable

---

src/dict/loaddictionaries.cc

opt: optimize the startup speed

---

.github/workflows/AutoTag.yml
.github/workflows/macos-homebrew-breakpad.yml
.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-6.x.yml
.github/workflows/windows.yml

https://github.com/xiaoyifang/goldendict-ng/issues/1031

action: unify tag and release tag name

---

src/ui/mainwindow.cc

fix: translate line in floatable toolbar will lose focus

---

src/ui/mainwindow.cc

Not sure if it is a bug in Qt.
close https://github.com/xiaoyifang/goldendict-ng/issues/1048
The `translateLine->setFocus();` is deleted because it is overridden later by the code inside `if ( !cfg.preferences.enableTrayIcon || !cfg.preferences.startToTray ) {`
After the show()/restoreState()/restoreGeometry(), no new widgets related to the main window will be created.

fix: adjust the order of Mainwindow's show() and restoreState/restoreGeometry

---

CMakeLists.txt

Fix `cmake --build build --target windeploy` does not find `windeployqt.exe` automically.

let cmake find windeployqt.exe

---

src/ui/mainwindow.cc
src/ui/translatebox.cc

fix: qcompleter lost signal when qlineedit lost focus

---

.github/workflows/AutoTag.yml
.github/workflows/macos-homebrew-PR-check.yml
.github/workflows/macos-homebrew-breakpad.yml
.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/ubuntu.yml
.github/workflows/windows-6.x.yml
.github/workflows/windows.yml

action: replace deprecated set-output with new syntax

---

src/config.cc
src/config.hh
src/ui/mainwindow.cc
src/ui/preferences.cc
src/ui/preferences.ui

opt: remove invalid index on exit

---

src/ui/scanpopup.cc

Fixes https://github.com/Ajatt-Tools/gd-tools/issues/5

fix: update globalbroadcaster translatelinetext also in scanpopup

---

src/ui/dictheadwords.cc

fix: the headwords got mixed together

---

src/config.cc
src/config.hh
src/main.cc
src/ui/preferences.cc
src/ui/preferences.hh
src/ui/preferences.ui

opt: add system font configuration

---

src/ui/mainwindow.cc
src/ui/translatebox.cc
src/ui/translatebox.hh

fix: translatebox press Enter does not translate the selected item

---

src/ui/mainwindow.cc

opt: make  translateline in toolbar the same height as toolbar

---

src/ui/translatebox.cc

fix: suggestion list scroll to the top

---

src/iframeschemehandler.cc

fix: website dictionary with port in the url

---

src/ui/scanpopup.cc
src/ui/translatebox.cc

fix: popup enter does not work

---

src/ui/mainwindow.cc
src/ui/scanpopup.cc
src/ui/translatebox.cc
src/ui/translatebox.hh

fix: enter event in translate textline

---

.github/workflows/macos-homebrew.yml

switch to official homebrew ffmpeg
`brew install ffmpeg`

fix: macos ffmpeg 

---

.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/windows-6.x.yml

qt 6.6.0 has not ready for use.

action: upgrade qt 6.6.0

---

.github/workflows/macos-homebrew-PR-check.yml
.github/workflows/macos-homebrew-breakpad.yml
.github/workflows/macos-homebrew.yml
.github/workflows/ubuntu-6.2.yml
.github/workflows/windows-6.x.yml
package-lock.json

from qt6.5 , ffmpeg has been the backend of qtmultimedia by default.

opt: remove ffmpeg player

---

.github/workflows/macos-homebrew.yml
.github/workflows/windows-6.x.yml
CMakeLists.txt
goldendict.pro
src/dict/sources.cc
src/version.hh
website/docs/howto/build_from_source.md

add option `CONFIG+=no_tts_support`
disable tts on macos/windows on Default.
the QSpeechtoText   has some issues which caused crash .

opt: add option to disable tts component

---

src/main.cc
src/ui/preferences.cc

opt: change font family

---

src/btreeidx.cc

fix: long headword cause crash

---

locale/crowdin.ts
src/ui/sources.ui

i18n: fix typo in Lingua Libre Dialog

---

src/ui/mainwindow.cc
src/ui/scanpopup.cc
src/ui/translatebox.cc

fix: word zoom does not work in completer

---

src/article_netmgr.cc
src/common/globalregex.cc
src/dict/mdx.cc

```
<audio controls src="xxx">
```
html5 audio ,video tag ,src attribute value changed to bres://

fix: reduce 206 response 

---

src/article_maker.cc
src/dict/dsl.cc
src/ui/mainwindow.cc

fix: dsl max width image

---

src/article_netmgr.cc
src/config.cc
src/config.hh
src/dict/dsl.cc
src/dict/dsl.hh
src/dict/loaddictionaries.cc
src/dict/loaddictionaries.hh
src/main.cc
src/ui/articleview.cc
src/ui/mainwindow.cc

relate https://github.com/xiaoyifang/goldendict-ng/issues/1197#issuecomment-1752047906

opt: remove gdpicture & maxPictureWidth which has not been used at all.

---

src/dict/dsl.cc

fix: dsl dictionary crash when creating full text index.

---

src/dict/dictserver.cc

fix: reduce wait time on socket

---

src/common/utils.cc
src/ui/scanpopup.cc

https://github.com/xiaoyifang/goldendict-ng/issues/1229#issuecomment-1757829680
Current:

opt: use italic to indicate the no results

---

src/dict/dictionary.cc
src/multimediaaudioplayer.cc
src/multimediaaudioplayer.hh

fix #1191 
only apply to qt>6.2

fix: audio device change handled

---

src/stylesheets/article-style.css

optimize the default css font

---

src/ui/articleview.cc
src/ui/articlewebview.cc
src/ui/articlewebview.hh

fix: mouse xbutton1(&2) back and forward event

---

src/dict/dsl_details.cc

fix: dsl encoding detection enhanced.

---

src/main.cc
src/ui/mainwindow.cc
website/mkdocs.yml

fix https://github.com/xiaoyifang/goldendict-ng/issues/1290

fix: force wayland should work for BSD

---

src/ftshelpers.cc

should not use equal( == ) comparision

opt: the address maybe not ordered

---

src/ui/stylescombobox.cc

fix: possible crash on macos

---

src/dict/sources.cc

opt: allow add directory in portable mode

---

.github/workflows/macos-arm-homebrew.yml
.github/workflows/macos-homebrew.yml
src/config.cc
src/dict/sounddir.cc
src/dict/sources.cc

* Update macos-homebrew.yml
* Update macos-arm-homebrew.yml

sync staged to dev

---

.github/scripts/windows-publish.ps1
.github/workflows/windows-6.x.yml
.github/workflows/windows-PR-check.yml
CMake_Win.cmake

just install the ffmpeg dlls from qt, and don't affect the former version.

A temporary workaround to #1451

---

src/ffmpegaudio.cc

resolve https://github.com/xiaoyifang/goldendict-ng/issues/1523
Although, Qt6.7 promotes the FFmpeg backend to default, all Linux distros previously make Qt multimedia depends on GStreamer backend rather than the FFmpeg one. 
I don't know, maybe this is not a good time to remove our in-home FFmpeg backend, so here is the trivial fix for the FFmpeg 7 compile.

fix: FFmpeg 7.0 compilation

---

src/dict/stardict.cc

fix issue mentioned in this https://github.com/goldendict/goldendict/pull/1695
unquoted attribute value.
https://regex101.com/r/eewsa0/1

fix: stardict unquoted attribute value

---

src/ui/mainwindow.cc

fix: when tab changes ,the tab page position reset to the start

---

src/ui/articleview.cc

fix: Scrollbar does not remember position

---

src/ui/articleview.cc
src/ui/articleview.hh
src/ui/mainwindow.cc

opt： tab icon change logic rewrite

---

src/article_maker.cc
src/ui/mainwindow.cc
src/ui/scanpopup.cc

fix: auto pronounce audio does not play

---

src/dict/slob.cc

fix: slob truncated file check.

---

src/dict/stardict.cc

fix #1585
fix some other issues:
https://regex101.com/r/tQOa7u/1
https://regex101.com/r/nnuuvW/1
https://regex101.com/r/zb4wBo/1
in #1587

fix: stardict regex invertedgreedy match

---

src/dict/dictionary.cc

:root css isolation
https://developer.mozilla.org/zh-CN/docs/Web/CSS/:root

opt: css isolation

---

src/common/globalregex.cc
src/dict/bgl.cc
src/dict/gls.cc

fix some other issues:
https://regex101.com/r/tQOa7u/1
https://regex101.com/r/nnuuvW/1
https://regex101.com/r/zb4wBo/1

opt: remove all the inverted greedy option

---

src/ui/articleview.cc

fix: links in webview got focused on default.

---

src/ui/mainwindow.cc
src/ui/mainwindow.hh

remove the logic ,seems have not affect the current function.

opt: remove wasMaximized logic of mainwindow

---

src/ui/articleview.cc
src/ui/scanpopup.cc

fix: Ctrl+F does not work in scanpopup dialog

---

src/ui/mainwindow.cc

This reverts commit 3a46dd290b995f7a0040bbe590ef26b4794a68fe.
the changes is not exactly the same.
close the last tab will cause the windows to create a new blank tab which will fall into infinite loop

Revert "clean: remove useless code and refactor"

---

src/ui/mainwindow.cc
src/ui/mainwindow.hh

fix: darkreader mode refresh

---

src/ui/articleview.cc
src/ui/mainwindow.cc

fix: refresh webview when changed darkreader mode

---

src/main.cc

opt: layout according to the language

---

src/ui/mainwindow.cc
src/ui/scanpopup.cc
src/ui/scanpopup.hh

workaround to solved the ctrl + f in scanpop dialog on macos

fix: set shortcut context

---

src/ui/articleview.cc

opt: do not show dictionary menu when set the dictionary count=0

---

src/ui/mainwindow.cc
src/ui/mainwindow.hh

This reverts commit 99c221c8549c131afc7526bf8391ecab46a82276.

Revert "opt: remove wasMaximized logic of mainwindow"

---

src/ui/mainwindow.cc

opt: valid zoomfactor range from 0.25 to 5

---

.github/workflows/PR-check-cmake.yml
website/docs/developer.md
website/docs/howto/build_from_source.md
website/mkdocs.yml

Replace https://github.com/xiaoyifang/goldendict-ng/pull/1663
close https://github.com/xiaoyifang/goldendict-ng/issues/1662

doc: exactly how to build GD in local machine

---

CMakeLists.txt

close https://github.com/xiaoyifang/goldendict-ng/issues/1687

dev: .ui files not showing in qt creator

---

src/dict/aard.cc
src/dict/bgl.cc
src/dict/dictdfiles.cc
src/dict/dictionary.hh
src/dict/dsl.cc
src/dict/epwing.cc
src/dict/gls.cc
src/dict/mdx.cc
src/dict/sdict.cc
src/dict/slob.cc
src/dict/stardict.cc
src/dict/xdxf.cc
src/dict/zim.cc
src/fulltextsearch.cc

the firstIteration is not used any more

opt: remove fulltext unused logic

---

.git-blame-ignore-revs
src/article_maker.hh
src/article_netmgr.hh
src/btreeidx.hh
src/common/utils.hh
src/config.hh
src/dict/epwing_book.hh
src/langcoder.hh
src/splitfile.hh

Amend https://github.com/xiaoyifang/goldendict-ng/pull/1739

clean: replace QVector & QPair in headers

---

src/main.cc

As suggested by: https://forum.freemdict.com/t/topic/11495/3445
To do this trick: https://superuser.com/a/37813

feat: allow changing icon on macOS by not overriding icon in Info.plist

---

CMakeLists.txt
locale/hu_HU.ts

Hi all,
I know you translate via CrowdIn, but I recently created original GoldenDict translation, and they use Qt .ts files. So I decided to update that file to your project too, since there were only ~120 differences of the total nearly 1000 strings.
I hope you can somehow magically push this file to CrowdIn so that further work can be done on it there. This is complete Hungarian translation, but I tested the GUI on the original version only. I have not tested this file on "-ng".
Thank you in advance if you will include it.
Keep up the good work! Maybe I should switch to "-ng".. I will see! ;-)

Adds Hungarian translation via .ts file

---

locale/hu_HU.ts
src/language.cc

Follow up of https://github.com/xiaoyifang/goldendict-ng/pull/1752
Hungarian GD:

feat: add Hungarian to Preferences and minor fix ts file

---

locale/hu_HU.ts

Follow up of https://github.com/xiaoyifang/goldendict-ng/pull/1752

Let Crowdin format Hungarian translation

---

website/docs/howto/build_from_source.md

add missing - in doc

---

src/multimediaaudioplayer.cc

close https://github.com/xiaoyifang/goldendict-ng/issues/1829

fix: Qt6.8 compile, QDebug error

---

.github/workflows/Release-all.yml

amend https://github.com/xiaoyifang/goldendict-ng/pull/1836

fix change log generation

---

src/article_netmgr.cc

https://github.com/qt/qtwebengine/blob/d48f8489882fc4106e514b6b267669c25980c78c/src/core/net/custom_url_loader_factory.cpp#L414C17-L423

opt: log more info about the stream

---

.github/workflows/Release-all.yml

close https://github.com/xiaoyifang/goldendict-ng/issues/1868
related https://github.com/xiaoyifang/goldendict-ng/issues/1738

fix: revert Qt from 6.7.3 to 6.7.2 for Speex (mdx) audios

---

src/dict/sources.cc

opt: hide website [as link] column

---

src/ui/sources.ui

opt: remove dictionary website extra word placeholders

---

src/article_maker.cc
src/config.cc
src/config.hh
src/ui/articleview.cc
src/ui/mainwindow.cc
src/ui/mainwindow.hh
src/ui/preferences.cc
src/ui/preferences.ui

related https://github.com/xiaoyifang/goldendict-ng/issues/1561
Change the type of bool -> tri state enum (so that we can have on/off/auto)
And change the checkbox to combobox
After

refactor: prepare config code to implement auto dark (reader) mode

---

src/article_maker.cc
src/config.hh
src/ui/mainwindow.cc
src/ui/preferences.cc

related https://github.com/xiaoyifang/goldendict-ng/issues/1561
demo:
https://github.com/user-attachments/assets/334096c3-e737-49c3-be2d-35f64ce0abfe

feat: auto dark reader mode that sync with the system

---

src/dict/bgl.cc
src/dict/mdx.cc

bgl tested with https://drive.google.com/drive/folders/0BzrQwK2v03aKWjlsQ3NsaWJKalU

clean: remaning deprecated `QCryptographicHash::addData` code

---

src/config.cc
src/config.hh
src/ui/mainwindow.cc

a few staffs missed in https://github.com/xiaoyifang/goldendict-ng/pull/1934 😅

disable more related to macOS trayicon -> dock icon

---

.clang-format
src/hotkeywrapper.hh
src/macos/machotkeywrapper.mm
src/macos/macmouseover.mm

I just set ObjC → `BasedOnStyle: Webkit` because XCode is the only thing to work on these files, and WebKit is maintained by Apple.
The diff looks pretty wild, because the original files have no formatting of any kind (every a few lines are different 😅).
There is almost no changes in these files, so git blame doesn't matter at all.

dev: .mm / obj-c files -> clang-format and simplify includes

---

src/common/folding.cc

scavenge https://github.com/xiaoyifang/goldendict-ng/pull/1945
Reduce 3 temp string to 2.
Impact is negligible nano sec level. Though the benchmarks consistently shows reduce (after thousands of repetitions). 
The optimizer is absolutely good. Some trickery can reduce time in debug more, but they are likely useless in release build.

opt: simplify Folding::apply

---

cmake/Deps_Unix.cmake

Homebrew is in a long migration of icu 75->76.
Now, libzim depends on icu4c@76.
Add rudimentary code to verify it.
(Random: 
I don't like any of these, but let's work with this for now.
I tried to use vcpkg on macOS before, but it doesn't work starting from here -> https://github.com/microsoft/vcpkg/pull/39600)

fix: macOS libzim <-> icu4c again and make mismatch a fatal error

---

src/dict/dictserver.cc

fix: [dictserver] some word does not got displayed

---

src/dict/stardict.cc

The `File::Index` is repurposed. This is the only odd place that uses it.

refactor: port StarDict -> Ifo away from File::Index

---

src/dict/aard.cc
src/dict/bgl.cc
src/dict/dictdfiles.cc
src/dict/dsl.cc
src/dict/gls.cc
src/dict/mdx.cc
src/dict/sdict.cc
src/dict/utils/dictfile.hh

redo https://github.com/xiaoyifang/goldendict-ng/pull/1435
(I don't like the ceremony of reading `dictionaryName`.)

clean: unify a common idx file read pattern uint32_t size + data

---

src/dict/hunspell.cc

Code was deleted partially in https://github.com/xiaoyifang/goldendict-ng/commit/49c6ae7032e0a133b85e196ac418d27883dbb9a9#diff-4bbfb55dd2b24097fdf2ce4ec8f7b9d006b7eb5f924668134d18d03bc65d9f93L648
And I find it entirely useless.
Hunspell::spell appears to assume utf-8 encoding. I don't find this info in doc though.
https://github.com/rrthomas/enchant/blob/d5346b19b294081d329d70bed0b4eccb09380f4d/providers/enchant_hunspell.cpp#L135-L143

clean: delete Hunspell::encodeToHunspell which is a synonym of utf32->utf8

---

.github/workflows/PR-check-cmake.yml
.github/workflows/Release-all.yml

fix https://github.com/xiaoyifang/goldendict-ng/issues/2013
The problem is not qt install problem btw.
It doesn't matter at all.
Just ignore it for now 😅

dev: ignore error when installing deps in macOS workflows

---

src/common/utils.hh
src/dict/dictserver.cc

opt: beautify the layout of dictserver output

---

src/common/folding.cc

opt: reorder the action

---

src/ui/mainwindow.cc

opt: combine the file filters as one entry

---

src/ui/mainwindow.cc
src/ui/scanpopup.cc

only change the font of translate line (QLineEdit)
result:
not the translate line in the dock area

opt: do not change font size of combobox and wordlist etc .

---

website/docs/topic_userstyle.md

I needed to search the code to find these options!
It would be nice to have them in the docs!

opt: update document for javascript customizations

---

src/common/utils.hh
src/ui/articleview.cc

fix: auto pronounce gdprg & gdtts

---

src/ui/favoritespanewidget.cc
src/ui/favoritespanewidget.hh

add function:  Clear all favorite items.
modify :
import favorite do not clear the existed items.

feat: favorite clear and import refactor

---

src/config.cc
src/config.hh
src/ui/edit_sources.ui
src/ui/edit_sources_models.cc

opt:remove romaji

---

CMakeLists.txt
vcpkg-configuration.json
vcpkg.json

For 
* https://github.com/xiaoyifang/goldendict-ng/issues/2094
---
Built by https://github.com/xiaoyifang/goldendict-ng/actions/runs/12938506497
New version https://github.com/xiaoyifang/goldendict-ng/releases/tag/vcpkg_250123_b588ddc8230705392c53448597f5892966a8db15
Previous version https://github.com/xiaoyifang/goldendict-ng/releases/tag/vcpkg_240711_3d72d8c930e1b6a1b2432b262c61af7d3287dcd0

update vcpkg artifact for windows build

---

CREDITS.txt
resources.qrc
src/ui/about.cc
src/ui/about.hh
src/ui/about.ui
src/ui/mainwindow.cc
src/version.cc
src/version.hh

close https://github.com/xiaoyifang/goldendict-ng/issues/1988
* Acknowledge every other contributors of the original GD project beside the initial author `ikm` who moved on to other things in life around 2013
* 2009 is the first commit by someone else.
* 2021 is basd on the date of this post https://forum.freemdict.com/t/topic/11495
* 2023 is the year when we split https://github.com/xiaoyifang/goldendict-ng/issues/489
* `GoldenDict Developers` is based on their discussions https://github.com/goldendict/goldendict/pull/1690
* `GoldenDict-ng Community` is based on my personal belief that writing code is not the only thing needed for turning software into a useful product, and this applies to open source software too. This acknowledges everyone involved.
* Refresh about dialog.

feat: update CREDITS and About dialog to acknowledge stakeholders

---

src/article_maker.cc
src/scripts/darkreader.js

maybe/(maybe not) related with #2102

opt:update darkreader version to 4.9.100

---

CMakeLists.txt

amend https://github.com/xiaoyifang/goldendict-ng/pull/2132

don't regenerate build_config.hh on every cmake rerun

---

src/dict/slob.cc
src/dict/zim.cc

https://github.com/qt/qtbase/blob/f1136de66638060b8a1ab9bc0cdf1a91dcb5ec01/src/corelib/io/qfilesystementry.cpp#L135-L143

clean: don't reinvent fileName();

---

src/dict/dictionary.hh
src/dict/epwing.cc
src/dict/xdxf.cc
src/stylesheets/article-style-st-lingoes-blue.css
src/stylesheets/article-style.css

amend https://github.com/xiaoyifang/goldendict-ng/pull/2140

amend commit 9463f70 for better load icon code

---

src/ui/scanpopup.cc

opt:add objectname to toolbar

---

src/dict/xdxf2html.cc

fix:rewrite the html generation

---

src/dict/dictionary.cc

fix https://github.com/xiaoyifang/goldendict-ng/pull/2139#discussion_r1957872156

fix custom dict icon loading with special chars `[]*?`

---

src/main.cc
src/ui/articleview.cc
src/ui/articleview.hh
src/ui/mainwindow.cc
src/ui/mainwindow.hh

fix:favorite headword retrieve logic

---

src/article_netmgr.cc
src/wordfinder.cc
src/wordfinder.hh

opt:refactor wordfinder,use signal/connect to handle single requestFinish event.

---

src/dict/loaddictionaries.hh

fix: temporary string cause crash

---

.github/workflows/Release-all.yml
cliff.toml

```
ERROR git_cliff_core::remote    > Request error: {"message":"API rate limit exceeded for 74.249.22.151. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

opt: git cliff api limit 

---

src/ui/favoritespanewidget.cc

https://github.com/xiaoyifang/goldendict-ng/pull/2203/files#r1972655916

fix: amend pr #2203

---

src/ftshelpers.cc

opt:full index add headword along with content

---

src/audio/multimediaaudioplayer.cc
src/audio/multimediaaudioplayer.hh

This reverts commit f8966785a1c3c252bb5823a019d4c05a2fe216db.
fix #2210

Revert "fix: multimedia memleak "

---

src/audio/multimediaaudioplayer.cc
src/audio/multimediaaudioplayer.hh

opt:use QScopedPointer instead of QPointer

---

src/dict/stardict.cc
website/docs/dictformats.md

close https://github.com/xiaoyifang/goldendict-ng/issues/2231

fix stardict res.zip loading and clarify related doc

---

src/dict/stardict.cc

Test result:
https://regex101.com/r/z3sJfH/1
https://regex101.com/r/yElt8H/1
test dict . https://github.com/nikita-moor/latin-dictionary/issues/2#issuecomment-496029572

opt:add stardict image support for http and base64 image

---

src/ui/scanpopup.cc

amend #https://github.com/xiaoyifang/goldendict-ng/pull/2221#issuecomment-2720564559

opt:add extra space at the right of search toolbar

---

src/dict/stardict.cc

opt:stardict resource file parse

---

locale/crowdin.ts
src/ui/chineseconversion.ui

https://en.wikipedia.org/wiki/Variant_Chinese_characters

opt:rename to more meaningful form

---

src/ui/mainwindow.ui
website/docs/ui_shortcuts.md

configuration folder should be a frequent used feature .

opt:add F11 as the shortcut to open configuration folder

---

src/dict/dsl.cc
src/scripts/gd-builtin.js

opt:dsl restrict area

---

src/ui/articleview.cc

fix:history back/forward navigation,audio playing issue

---

src/audio/multimediaaudioplayer.cc

https://github.com/xiaoyifang/goldendict-ng/issues/2251#issuecomment-2747048787

opt:safeguard to reset source

---

.github/workflows/Manual-Build-Action.yml
.github/workflows/PR-check-cmake.yml
.github/workflows/Release-all.yml
.github/workflows/auto format.yml

opt:action input variable

---

src/language.cc
src/language.hh
src/ui/preferences.cc

Replaced manual locale listing with a more efficient iteration using `Language::languageMap`. This improves maintainability and reduces redundant code, ensuring a cleaner and more consistent approach to language handling.

opt: Refactor language loading logic in preferences UI.

---

src/common/iconv.cc

fix:epwing dictionary crash when meet certain diacritics

---

src/dict/transliteration/custom.cc
src/dict/transliteration/transliteration.cc
src/dict/transliteration/transliteration.hh

fix:custom trans does not work

---

src/ui/preferences.cc

fix:use ui control's checkable state

---

website/docs/howto/how to use breadpad crash analysis.md

The VS option is much more superior.

doc: update breakpad doc to state-of-art

---

src/instances.cc
src/instances.hh
src/ui/mainwindow.cc

delete none-const version of Groups::findGroup

delete none-const version of Groups::findGroup

---

src/ui/articleview.cc

Reverts xiaoyifang/goldendict-ng#2425
https://github.com/xiaoyifang/goldendict-ng/issues/2424

Revert "fix: audio click link could fallback to other dicts in the same group"

---

locale/crowdin.ts
src/article_maker.cc
src/config.cc
src/config.hh
src/dict/dictionary.hh
src/dict/website.cc
src/ui/edit_sources_models.cc

- remove embed html logic
- move `open website in seperate tab widget` logic to WebSite class

opt:website dictionary refactor

---

src/config.cc
src/config.hh
src/history.cc
src/history.hh

opt:history save with Write-Ahead Log

---

locale/crowdin.ts
src/article_maker.cc
src/article_maker.hh
src/dict/dictionary.cc
src/dict/dictionary.hh
src/dict/mdx.cc
src/dict/slob.cc
src/dict/website.cc
src/dict/zim.cc

opt:support :about to render description page

---

src/config.hh

Remove redundant constructors, keep the version with default script parameter, simplify code structure

refactor(config): Merge WebSite constructors with default parameters

---

src/scripts/gd-custom.js

fix:gdlookup do not need to restrict to certain dictionary.
