.github/workflows/macos-m1.yml
like this:
https://github.com/ngn999/goldendict/releases/tag/v22.4.7-alpha.2204100313.30ddc081-m1
the github action only opens a blank draft release, then I can upload the dmg file, and release it.
I heard about draft release from here: https://github.com/railwaycat/homebrew-emacsmacport/blob/master/.github/workflows/emacs.yml
this repo provides a apple silicon package.
=> we can upload Apple Silicon version manually

mainwindow.cc
MainWindow::showTranslationFor() overloads disable the "Pronounce Word"
action, then call ArticleView::showDefinition(). And then immediately
update pronounce availability, Found in Dictionaries list, Back and
Forward buttons. Since ArticleView::showDefinition() loads the requested
page asynchronously, the previous page is still current. Therefore the
"Pronounce Word" action is immediately re-enabled (if the still-current
article has sounds), the other state updates have no effect whatsoever.
Once the new page is loaded, the state is updated again in
MainWindow::pageLoaded() - this time with the desired effect.
So the only effect of the state updates in
MainWindow::showTranslationFor() is to revert the intentional disabling
of the "Pronounce Word" action. Plus waste some CPU time. The …
=> Don't update state prematurely in showTranslationFor()

gddebug.cc
the gdDebug gdWarning method,  set the QTextCodec, does not seem to take effect
=> remove uselesscode

articleview.cc, articleview.hh
https://doc.qt.io/archives/qt-5.5/qtwebkit-bridge.html#internet-security
Qt WebKit Bridge documentation recommends:
When exposing native objects to an open web environment, it is
important to understand the security implications. Think whether the
exposed object enables the web environment access things that
shouldn't be open, and whether the web content loaded by that web page
comes from a trusted source.
The author of Qt WebChannel has said the following in a talk that
introduced this Qt module (WebKit Bridge replacement for Qt WebEngine):
My suggestion here is to write dedicated QObjects with a slim, minimal
API that only have the signals and methods that you deem safe to be
used from the outside.
- see a comment under https://redirect.invidious.io/watch?v=KnvnTi6XafA
=> ArticleView: expose only minimal API to JavaScript

articleview.cc
201f11e65638365e7ef996bf43386581ff4bd075 missed this possibility and may
have inadvertently changed the application behavior in a corner case.
=> setCurrentArticle(): return false if the article doesn't exist

ffmpegaudio.cc
Since the update to FFmpeg 5.0, when FFmpeg+libao internal player is
selected, most sounds fail to be pronounced. Furthermore, each failed
pronunciation attempt increases GoldenDict's CPU usage. Finally,
GoldenDict continues to hang and utilize the CPU cores when the user
attempts to exit it.
The reason for the issue is: GoldenDict's readAudioData() returns 0 at
EOF but FFmpeg expects the callback to return AVERROR_EOF. As a result,
internal player's threads are busy calling readAudioData() indefinitely.
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/a606f27f4c610708fa96e35eed7b7537d3d8f712
documented the expected return value of the read_packet callback.
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/252500a78fe1a31abc79e6070d16f50382c39343
removed the code that handled the deprecated …
=> FFmpeg 5.0 player: stop reading raw data at EOF

articleview.cc
When searching in webengine (with Ctrl+F) the program will crash with a segmentation fault, with console printing the following:
```bash
...
...
====reading 14798 bytes
js: Uncaught SyntaxError: Identifier 'OxfordTagSwitchCN' has already been declared
article view loaded url: "gdlookup://localhost?word=test&group=4294967294" true
getResource: b
scheme: b
host: 5
fish: Job 1, 'goldendict' terminated by signal SIGSEGV (Address boundary error)
```
This is caused by capturing a reference of a QString in a callback. When the callback is invoked the captured QString might already be deconstructed thus causing a segmentation fault. Capture by copy fixes the issue.
=> Fix crash when search in webengine

iframeschemehandler.cpp
in current qt6.3.1 version ,there is  a regression that the 404 response with no response body.
this is a workaround waiting for the fix in Qt6.4.1
=> fix: word around to fix website return 404 with no response body

about.cc, about.hh, about.ui, mainwindow.cc
This will probably reduce the useless conversation of asking bug reporter's basic system info. They can just click that button rather than screenshot.
It will include flags only for linux users since they often build things themselves.
Sample output:
```
Goldendict 22.9.24-alpha.67485fd8 on Thu Nov 17 02:59:57 2022
arch linux 6.0.8-arch1-1 Qt 5.15.7 x86_64-little_endian-lp64
GCC 12.2.0
Flags: MAKE_EXTRA_TIFF_HANDLER
```
The "copy dictionaries list" does feel useless and i didn't figure out how to get what type of dict that a user are using. It is just a list of names.
Since qt6 requires c++17, i think the lambda usage is ok.
=> Add two basic "copy info" buttons to about dialog for easier bug reporting

config.cc, config.hh, keyboardstate.hh, mainwindow.cc, mainwindow.hh, preferences.cc, preferences.hh, preferences.ui, scanflag.cc, scanflag.hh, scanpopup.cc, scanpopup.hh
This implemented the design described here: https://github.com/xiaoyifang/goldendict/issues/203#issuecomment-1320880904
The commits are atomic, each one only does a little thing and reviewing them one by one should be easy.
I don't quite understand how this works because we have two `clipboardChange()` in `mainwindow.cc` and `scanpopup.cc`. They seem to do the same thing, but one of them is rather simple and another one is full of hacks. Both of them connect to a bunch of things.
The two implementations are both connected to the clipboard change event.
https://github.com/xiaoyifang/goldendict/blob/dc29111e880bec6b2bc98e39f2ec4221491667c0/scanpopup.cc#L284
https://github.com/xiaoyifang/goldendict/blob/dc29111e880bec6b2bc98e39f2ec4221491667c0/mainwindow.cc#L921
fix …
=> Overhaul ScanPopup

goldendict.pro
They are only useful for win & mac's build.
fix https://github.com/xiaoyifang/goldendict/issues/213
This shouldn't break anything for linux. We already use /usr/share/...../local one
https://github.com/xiaoyifang/goldendict/blob/4f10a55f958f0b39252dbc3c3dc47374ef8ab919/goldendict.pro#L171
https://github.com/xiaoyifang/goldendict/blob/75a83b0f8182eb4a6fe95d3fd24f08f84d584680/config.cc#L2229
https://github.com/xiaoyifang/goldendict/blob/75a83b0f8182eb4a6fe95d3fd24f08f84d584680/config.cc#L2239
=> Fix translations accidentally installed at /local

main.cc, mainwindow.cc, redist/org.goldendict.GoldenDict.desktop
To test this, try `goldendict://nice` on explore.exe's address bar, browser or any editor that supports hyperlinks.
This is an unobvious feature, probably we should document it somewhere, like the wiki or put it in "changes.md" which seems not updated anymore.
If the goldendict already running, GD will use the popup to show the result.
Related:
Fixes https://github.com/xiaoyifang/goldendict/issues/221
Fixes https://github.com/goldendict/goldendict/issues/735
=> Implement "goldendict://nice" url scheme handler for windows and linux

ffmpegaudio.cc
the 2nd parameter is useless when context->pd is not null
=> ffmpeg , replace avformat_open_input's second parameter to NULL

fulltextsearch.hh
It is really my bad. This QTimer will live in a thread, if it is gone, then GD will crash.
It's parent must be null.
~~A better fix is probably not putting it here.~~
=> fix: revert QTimer change

aard.cc, article_maker.cc, base/globalregex.cc, bgl.cc, dictdfiles.cc, dictionary.cc, dictserver.cc, dsl.cc, dsl_details.cc, epwing_book.cc, folding.cc, forvo.cc, gls.cc, htmlescape.cc, hunspell.cc, loaddictionaries.cc, lsa.cc, mainwindow.cc, mdx.cc, mediawiki.cc, programs.cc, sdict.cc, slob.cc, sounddir.cc, stardict.cc, voiceengines.cc, website.cc, zim.cc, zipsounds.cc
Apply this clang-tidy check:
https://clang.llvm.org/extra/clang-tidy/checks/modernize/raw-string-literal.html
We have a lot of HTML and regex-related strings. All of them are too hard to read.
The changes are automatically made by:
```bash
cd build/
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
run-clang-tidy -checks="-*,modernize-raw-string-literal" -fix
```
The `run-clang-tidy(.py)` is included in newer versions of clang.
A `.clang-tidy` should be added to enforce this, and that's the next PR.
=> Modernization: Use raw strings instead of escaping everywhere

.clang-tidy
1st line `-*` remove all check
then add what we need
like all checks under `modernize-*,`
then remove checks that don't make sense on our code base.
the `-` prefix is to remove a check.
---
I think this aggressively enables more checks than the default of Qt Creator.
More warnings maybe popup in that IDE.
Some other checks maybe also don't make sense in our codebase, we can remove them when needed.
https://clang.llvm.org/extra/clang-tidy/
=> dev: add .clang-tidy

.clang-tidy, loaddictionaries.cc, loaddictionaries.hh
The original code from 10+ years ago is slow and unreadable.
Old code:
It uses `{ }` to create a scope so that a temporal variable will be created and deleted later.
the `dictionaries` is a vector, and the `insert()` will _copy_ the value of `Dictionary::Class` to the vector's storage one by one. The original temporal vector will be destroyed later.
For a Dictionary::Class, it will be created -> assembled to a vector -> assigned to a temporal vector -> copied to the vector `dictionaries` (-> destroy the temporal one)
```
{
vector< sptr< Dictionary::Class > > mdxDictionaries =
Mdx::makeDictionaries( allFiles, FsEncoding::encode( Config::getIndexDir() ), *this );
dictionaries.insert( dictionaries.end(), mdxDictionaries.begin(),
mdxDictionaries.end() );
}
```
---
The new code:
```
void …
```
=> Simplify and speed up dictionary loading

.gitignore, article_maker.cc, config.cc, config.hh, locale/zh_CN.ts, mainwindow.cc, mainwindow.hh, preferences.cc, preferences.ui
For Linux & mac users and also for users who don't like white text on dark
`applyQtStyleSheet`'s 1st parameter is removed because we don't do Qt styling based on article view's style anymore.
The `type` in <script> is useless since we use webengine and html5. HTML5 formally recognizes javascript as the one true script for the web, so I deleted it as recommended by the standard.
https://html.spec.whatwg.org/#the-script-element
---
Possible further improvements,
The preference dialog could use some reorganization, but that belongs to another PR.
The ceremony of adding a new option is insane. The `config.cc` should get a cleanup.
close https://github.com/xiaoyifang/goldendict/issues/271
=> Add option to enable Dark Reader mode

mainwindow.cc, mainwindow.hh
Remove all other "Ctrl+H" other than the one in the .ui file.
https://github.com/xiaoyifang/goldendict/blob/bcfa3f0bd41dc8c84f94a1d760d1202bfa36d377/mainwindow.ui#L475-L481
All other buttons in other places are just normal QAction that don't need special treatments.
https://github.com/xiaoyifang/goldendict/issues/279
=> refactor: remove duplicated history shortcut setting

articleview.cc
For local sound files, the O is in conflict
Related
https://forum.freemdict.com/t/topic/14791/12
https://github.com/xiaoyifang/goldendict/issues/282
After:
The E is chosen because
For external links, the shortcut is E
=> fix: shortcut conflict

mainwindow.cc, scanpopup.cc, scanpopup.hh
ScanPopup::clipboardChanged isn't used (I put a [[deprecated]] a month ago).
Now all the remaining functionalities are moved to Mainwindow::clipboardChanged
* ignoreOwnClipboardChanges -> ignore change if app owns the clipboard change
* delay timer to prevent slow selection -> frequent refreshing
Thus it is removed.
---
The reason why we bloat Mainwindow with yet another method is:
to access the 💡 enableScanningAction.ischecked() :facepalm:
We can move those lines away from MainWindow by just adding a variable -> isScanningActionChecked plus two methods of `scanpopup.enable()/disable()`
---
Actually, the original design is using a var inside `scanpopup.cc`, but handling logic all in mainwindow::clipboardChanged() also makes scene since all codes are in one place without the need to …
=> fix remaining problems of scanpop clipboard on linux

.clang-tidy, aard.cc, articleview.cc, bgl.cc, btreeidx.cc, chinese.cc, dictdfiles.cc, dictserver.cc, dsl.cc, epwing.cc, forvo.cc, gls.cc, hunspell.cc, lsa.cc, mainwindow.cc, mdx.cc, mediawiki.cc, programs.cc, sdict.cc, slob.cc, sounddir.cc, stardict.cc, voiceengines.cc, website.cc, xdxf.cc, zim.cc, zipsounds.cc
use the same technique as https://github.com/xiaoyifang/goldendict/pull/270
If the base class method is set to `virtual`, then the derived class should be `override`.
Using `virtual` for both the base class and derived class is a design flaw of C++98, however, switching to override won't change anything if they are already correct.
https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-override.html
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final
=> clang-tidy: apply modernize-use-override

mainwindow.cc
The previous code is broken because `articleMaker.setDisplayStyle` and `applyQtStyleSheet` used to be the bundled together. 
https://github.com/xiaoyifang/goldendict/pull/288 only fixes half of the problem
=> fix: reload all pages when articleview style changes

config.hh, dictgroupwidget.ui, groups_widgets.cc
Users can now set absurd shortcuts for group switching like this and it works.
for qt6.4+
see https://github.com/xiaoyifang/goldendict/issues/291
=> replace dict group's hotkeyedit with qKeySequenceEdit

goldendict.pro
the opening brace must stand on the same line as the condition, otherwise the condition will be invalid.
---
and fix qtmultimedia dependency
audiooutput.cpp includes the QAudioFormat unconditionally, but it looks
like this file is only used by ffmpeg_player and qtmultimedia_player,
so add an extra condition to append this file and its header.
=> fix: 'equals' built-in test function block

qt-style.css
close https://github.com/xiaoyifang/goldendict/issues/327
I still don't know why padding must be set so that the dropdown list's text won't elide.
I tried to set `GroupComboBox().view().setTextElideMode(Qt::ElideNone)` but it doesn't work.
=> fix: group combo box isn't centered

article_maker.cc
Fix one problem discussed at https://github.com/xiaoyifang/goldendict/issues/339
When dark reader is enabled:
Before:
After:
=> fix: reset background to white when darkreader mode is used

src/qtstyle/qt-style.css
=> fix: ensure #translateLine always have left border

mainwindow.cc, mainwindow.hh, scanpopup.cc, scanpopup.hh
This PR is supposed to have absolutely no behaviour change.
Why?
In the original GD, the existence of object `ScanPopup` is a convoluted mess. It checks multiple factors, including `enable ScanPopup`, `toolbar's Scanpopup action checked`. `scanpopup hotkey enabled`.....
And it is OK to do so, but the later code is a mix of checking scanpop's existence `if(ScanPopup)` and other factors. If data related to ScanPopup changed, the old code just `reset()` ScanPopup then rebuild it with `makeScanPopup()`.
As a result, the old code goes insane, and I have no idea what's going on with the scanpopup, so during https://github.com/xiaoyifang/goldendict/pull/207 , the ScanPopup is changed to be a persist object that always exist (the memory consumption isn't increased noticeably).
---
This PR removes …
=> elimate makeScanPopup()

article_maker.cc
fix https://github.com/xiaoyifang/goldendict/issues/357
darkreader.js is not a simple colour inverter. Setting the initial background to Black instead of White should fix the problem.
(the value must be almost black, because darkreader.js won't adjust pure black.)
.gdarticle will be reset to no background (transparent)
=> fix: set initial background as black for dark reader mode

mainwindow.cc, mainwindow.hh
fix https://github.com/xiaoyifang/goldendict/issues/361
main change:
From this line that only change UI widget's state:
```
enableScanningAction->setChecked( true );
```
to this that activate the action which change Both UI widget's state and setup scanning :
```
enableScanningAction->trigger();
```
=> fix: enabled scanpopup at startup doesn't work

article-style-st-babylon.css, article-style-st-classic.css, article-style-st-lingoes-blue.css, article-style-st-lingoes.css, article-style-st-modern.css, article-style.css, article_maker.cc, article_netmgr.cc, dsl.cc, epwing_book.cc, forvo.cc, gls.cc, lsa.cc, mediawiki.cc, programs.cc, scripts/gd-builtin.js, sounddir.cc, src/dict/lingualibre.cpp, stardict.cc, voiceengines.cc, xdxf2html.cc, zipsounds.cc
Mostly from @vedgy's fork
https://github.com/goldendict/goldendict/commit/c415cede8509b1bc431fbda81f681c95be0281e0
https://github.com/goldendict/goldendict/commit/bb06509582c9a1ab342f5b79c85c3e28a26b19bc
ALL qrcx://localhost were used to fetch some pictures. 
The `qrcx` is just `qrc` but with extra steps
https://github.com/xiaoyifang/goldendict/blob/2404a5d34118b47eb3b8ca6fe0828305f697c1c3/article_netmgr.cc#L147-L159
=> cleanup: Replace all usages of qrcx://localhost with qrc://

mdx.cc
```
<a id="xxx"></a><p></p>
<a name="xxx"></a><p></p>
<a id="xxx" name="xxx"></a><p></p>
```
hashtag does not work on the above anchors.
=> fix: anchor #hashtag navigation failed to work

config.cc, config.hh, mainwindow.cc, preferences.cc, preferences.ui, scanpopup.cc
When a search is triggered, the main window focuses itself even if it's already visible, which may be undesirable for some users. Let the user disable this behavior.
=> Let the user disable main window stealing focus when searching.

article-style-st-babylon.css, article-style-st-lingvo.css, article-style-st-modern.css, article_maker.cc, articlewebview.cc, articlewebview.hh, src/ui/articleview.cpp
https://github.com/xiaoyifang/goldendict/issues/357
This fix is bad, but it does reduce the white flash greatly.
* Swap out `webview` when a page Loading started
* Immediately set the page's background to black after the `<html>` tag
* Delayed swapping back (200ms) to cover a glimpse of white during page Rendering
* Set the initial background of QWebEnginePage to black (which only affect the background when creating a new tab)
=> fix white flash in dark reader mode

base/globalregex.cc, base/globalregex.hh, epwing.cc, epwing_book.cc, epwing_book.hh, locale/zh_CN.ts
Ｅｐｗｉｎｇ　is designed for ebook. used as dictionary is not quite supported.
epwing use ref links to navigate to **any place** in the ebook .  the place may not a a dictionary headword.
before this commit:
reference in some dictionaries has the following effect.
after:
compared to ebwin
=> feature: epwing dictionary reference navigation improved.

article_maker.cc, article_maker.hh, mainwindow.cc, mainwindow.hh, scanpopup.cc, scanpopup.hh, src/ui/articleview.cpp, src/ui/articleview.h
The original code is extremely convoluted because the code was passing a "AlwaysExpand" from Mainwindow <> ArticleView <> ArticleMaker back and forth and back and forth via signals.
https://github.com/goldendict/goldendict/commit/305c9ed1b8acb36746d7d8a410417e945eaf67b1
Save this file as `test.dsl`
```
#NAME "test"
#INDEX_LANGUAGE "English"
#CONTENTS_LANGUAGE "English"
a
[m1]ok[*]: what is this [/*][/m]
```
The "Expand mode" (Lingvo call it "Full translation mode") is a "+" toggle for text between the `[*][/*]`
If the "AlwaysExpand" is turned on, the "+" toggle will be gone, and the text between`[*][/*]` will always be shown.
And that's all.
Why the original code has so much signals connected together?
They are used to toggling "AlwaysExpand" mode for a single ArticleView (Single Tab) via …
=> cleanup: simplify DSL's expand mode

.clang-format, article_maker.cc, article_maker.hh, mainwindow.cc
Replace https://github.com/xiaoyifang/goldendict/pull/403
Now the code make sense. If any of the 6 parameters changed, reload().
=> cleanup: remove unnecessary variables in ArticleMaker

bgl.cc, bgl_babylon.cc, dictdfiles.cc, dictionarybar.cc, favoritespanewidget.cc, ffmpegaudio.cc, gdappstyle.cc, history.cc, historypanewidget.cc, iconv.cc, indexedzip.cc, lsa.cc, main.cc, mainstatusbar.cc, maintabwidget.cc, sdict.cc, sounddir.cc, stardict.cc, translatebox.cc, wordlist.cc, xdxf.cc, xdxf2html.cc, zim.cc, zipsounds.cc
Their existence has no purpose.
qDebug is part of `<QtGlobal>` which is included by almost all other headers.
https://doc.qt.io/qt-6/qtglobal.html#details
=> cleanup: remove all useless #include <QDebug>

ankiconnector.cpp, ankiconnector.h, src/ui/articleview.cpp
This PR lets any external program create "ankisearch:" links. By clicking on such link, the Anki Browser opens with the specified query.
https://user-images.githubusercontent.com/69171671/226745860-e9eef053-518b-471b-8154-126c9e0755c6.mp4
This can be useful to check if you already have a certain word added to Anki.
=> Allow adding "ankisearch:" links in external programs.

globalbroadcaster.h, locale/ru_RU.ts, mainwindow.cc, programs.cc, sources.ui
This PR allows the contents of the search bar to be passed to external programs, using the %GDSEARCH% keyword. 
This could be useful for programs like Mecab that split sentences into individual words. You could look up a full sentence, then click on the individual words, but the sentence will not disappear since it is passed as a separate argument.
Without this PR it is hard to implement since %GDWORD% changes every time you click on a new word.
Example: 
https://user-images.githubusercontent.com/50422430/226139459-0c8bcf0e-e68f-491e-8171-bae3f50a7ae1.mp4
=> give external programs access to translateLine via %GDSEARCH%

ankiconnector.cpp, ankiconnector.h, article-style.css, article_maker.cc, article_maker.hh, config.cc, config.hh, icons/add-anki-icon.svg, resources.qrc, src/ui/articleview.cpp, src/ui/articleview.h
This PR adds a "make a new anki note" button to each article if the user has configured Anki integration in Preferences. Pressing the button results in a new Anki note being added to one's Anki deck, with the corresponding article's text as the definition. If there is selected text, it will be sent instead, similarly to the context menu action that was added before.
Having a button allows to mimic more closely the process of creating Anki cards with Yomichan. Yomichan also places a `+` button next to each search result on the right side.
Screencast:
https://user-images.githubusercontent.com/69171671/229608231-9cca36f0-8656-42b2-aaaa-ac61ad2c2f4a.mp4
=> Add "make anki note" buttons to displayed articles.

article_maker.cc, epwing.cc
for  reference links ,  add the text which  the reference link pointed to as a synonym .
In epwing dictionary, the reference link can be at any place , not only limited to the headword.
it can point to any position in the article text
=> epwing: add Synonym search

termination.cc
GD's exceptions right now are mostly defined with this
https://github.com/xiaoyifang/goldendict/blob/21fa719c03b358531effc6de91dba3d572715395/ex.hh#L9-L18
https://github.com/xiaoyifang/goldendict/blob/37a08d45d3db1a4a45e68a33d9277227f091ec6e/slob.cc#L67
The code has a problem: they are all unhandled. If the code calls `throw exName()`, they will end up in the `termHandler` with a message "GoldenDict has crashed with an **unexpected exception**", the `exDescription` is not used in anywhere.
This PR added a trick to display the `exDescription` so that we can know exactly where are the "expected" crash happens.
The original code use a similar method, but the method is not portable.
https://github.com/goldendict/goldendict/blob/8834e4a2924d143751870f4b943c3ce608b10a7d/termination.cc#L38-L42 …
=> Display exception description when unhandled exception got thrown

mainwindow.cc, mainwindow.hh, mruqmenu.cc, mruqmenu.hh, preferences.ui
Merge
* `MainWindow::ctrlReleased`
* `MRUQMenu::eventFilter` 
Into
* `MRUQMenu::keyReleaseEvent`
http://goldendict.org/forum/viewtopic.php?f=4&t=1176
* enable "Preferences" -> "Interface" -> "Ctrl-Tab in MRU order"
* Ctrl+tab -> the tab menu will show, when finished, the selected one will become topmost.
=> simplify MRU ctrl release handling

dictionarybar.cc, dictionarybar.hh, editdictionaries.hh, mainwindow.cc, mainwindow.hh, orderandprops.cc, orderandprops.hh
`connect` related to `showDictionaryHeadwords` cannot be converted to the new syntax
https://github.com/xiaoyifang/goldendict/blob/e32a7a2c94fd97f25f3f66d52d38106b09317138/mainwindow.cc#L547-L550
because there are two versions
1. `showDictionaryHeadwords( const QString & id )`
2. `showDictionaryHeadwords( QWidget * owner, Dictionary::Class * dict )`
-> (1) wraps around (2) with extra code that obtain owner and loop through `dictionaries` list to match the `id`.
The existence of (2) is useless because both `owner` and `dict` can be derived from `id`.
Instead of passing a string `id` and loop through the dictionary list to obtain `Dictionary::Class * dict`, just pass the `Dictionary::Class * dict` and show its head word.
The loop is removed :)
Cases where the dialog is NonModal -> click a …
=> Simplify MainWindow::showDictionaryHeadwords

groups_widgets.cc
Calling append() on a copy of a QVector detaches and makes a deep copy of the container. Modify the QVector in-place to prevent copying and thus improve performance.
=> Avoid copying a QVector

aard.cc, bgl.cc, dictdfiles.cc, dictinfo.cc, dictionary.cc, dsl.cc, epwing.cc, epwing_book.cc, file.cc, fsencoding.cc, fsencoding.hh, gls.cc, groups_widgets.cc, hunspell.cc, loaddictionaries.cc, lsa.cc, mainwindow.cc, mdx.cc, orderandprops.cc, sdict.cc, slob.cc, sounddir.cc, splitfile.cc, stardict.cc, xdxf.cc, xdxf2html.cc, zim.cc, zipsounds.cc
Rename a dict path to `😎whatرحبًا你好¡Hola!💩` and GD still works :)
Tested on Linux & Windows11.
`Qt_Method(FsEncoding::decode(a_std_string.c_str()))` is converted to `Qt_Method(a_std_string.c_str())`, becuase all related Qt_methods can take `char *`. A few places are converted to `Qt_Method(QString::fromStdString(a_std_string))`.
`FsEncoding::encode(a_QString)` is converted to `a_QString.toStdString()` or `a_QString.toUtf8()` (They are equivalent).
---
https://github.com/xiaoyifang/goldendict/issues/468
=> Remove FsEncoding::encode/decode

dictionary.cc, dictionary.hh, dsl.cc, fsencoding.cc, fsencoding.hh, gls.cc, mainwindow.cc, mdx.cc, stardict.cc, xdxf.cc, xdxf2html.cc
`FsEncoding::dirname` is removed :smile: 
`FsEncoding::dirname` is always used with `getDictionaryFilenames()[ 0 ]` to obtain the `containingDir` of a dictionary, with one exception at `stardict.cc`
Due to previously usage of std::string for path storage, this has to include a `toStdString()` for now.
The most beautiful change in this PR:
https://github.com/xiaoyifang/goldendict/issues/468
=> Abstract `FsEncoding::dirname(getDictionaryFilenames()[0])` into `Dictionary::Class::getContainingDir`

config.cc, config.hh, preferences.cc, preferences.ui, src/ui/articleview.cpp
this plugin is used mainly for flash plugins, which has been disabled in modern browser. There is no need to configure this option.
fix #481
=> fix: remove the webplugin option

.clang-format, file.cc, file.hh
After `File::Class`'s migration from `FILE` to `QFile` https://github.com/xiaoyifang/goldendict/commit/becc74c730d350e06cc58cea3396a4e4ce82c3bf , the buffer is no longer useful because `QFile` already did that.
---
This PR is intended to avoid any change outside `file.cc/file.h`. The new implementation is a drop-in replacement. If unforeseeable bugs ever happen, we can revert without problem :)
---
To minimize changes, the `QFile` is hold as `f` as before, because of the name confliction between the template read(). If we change the template's name, all files will need a change. Also, we don't want all QFile's API to be exposed.
https://github.com/xiaoyifang/goldendict/issues/468
=> Remove the WriteBuffer from File::Class

stardict.cc
Background: https://github.com/nikita-moor/latin-dictionary/issues/2#issuecomment-496029572
It is not implemented since 2009.
Fix this dict
https://github.com/xiaoyifang/goldendict/blob/54a4a052a5a09dbb6994b4eb58ef2196545be450/config.cc#L479
Which can be obtained from stardict's source tree
https://github.com/huzheng001/stardict-3/tree/master/dict/src/dic/stardict-dict
Or install the `stardict` package on Linux.
When encounters `r` inside the `*.dict` file ⇾ convert `img:wenjing.png\nimg:wenjing2.png` into `<img src="bres://{dict_id}/wenjing.png">`
Then you can see the that stardict's author shipped that girl's image to every linux distro :)
=> Stardict: display `img:` in resource file list ('r'); support stardict's demo dict

article_maker.cc, article_maker.hh, article_netmgr.cc, articlewebview.cc, articlewebview.hh, config.cc, config.hh, globalbroadcaster.h, locale/zh_CN.ts, preferences.cc, preferences.ui, scripts/gd-builtin.js, src/ui/articleview.cpp, src/ui/articleview.h
when enabled , user's manual collapsed dictionary will remain collapsed in the successive search until user expand the dictionary again.
fix #115
=> feat: session collapsable feature support

article_maker.cc, base/globalregex.hh
if the start div is `<div>` ,the actual result will has an extra html closed tags .
fix  https://github.com/goldendict/goldendict/issues/1617
=> fix: findEndOfCloseDiv does not work as always

src/ui/articleview.cc, src/ui/mainwindow.cc, src/ui/scanpopup.cc
can not type word directly again.
fix:#185
the fix has a side-effect ,  for example, in the history panel , press `s` will be redirect to translateline inputbox.
should this be respected and navigate through the history panel.
Though the above side-effect can be fix,what's your opinion from user perspective @itkind
=> fix: when input word in translateline and press Enter

CMakeLists.txt, src/macos/gd_clipboard.cc, src/macos/gd_clipboard.hh, src/macos/macmouseover.hh, src/ui/about.cc
* Xapian by default
* Recursive file finding
All files are .cc/.hh now, so I just add all of them with wildcard => we don't have to update it at all :)
Because we still have to use qmake/Qt5 for some time, we don't have to worry about accidentally adding some files by accident.
=> CMake Updates

src/fulltextsearch.cc, src/fulltextsearch.hh, src/ui/dictheadwords.cc, src/ui/editdictionaries.cc, src/ui/mainwindow.cc, src/ui/mainwindow.hh
Reduce compile time,
`editdictionaries.cc` and `dictheadwords.cc` doesn't need it
`fulltextsearch.cc` has a useless `static_cast<Mainwindow*>`
Type a word on search box -> Open Full text search dialog, the word is automatically on the dialog's search box.
=> Reduce include dependency on `mainwindow.hh`

src/ui/groups_widgets.cc, website/docs/manage_groups.md
fix https://forum.freemdict.com/t/topic/20678/7
New code will check if `container folder's dirname()` (aka groupName) has duplications. If yes, then set dirNeedPrepend to true.
When inserting paths to groupToDicts, two levels of names (like `epistularum/japanese`) will be inserted.
---
This structure will be grouped into `john/english` and `tomy/english` [test_autoFolderGrou.zip](https://github.com/xiaoyifang/goldendict-ng/files/11330251/test_autoFolderGrou.zip)
```
.
├── john
│   └── english
│       └── a&b
│           ├── a.dsl
│           └── b.dsl
└── tomy
└── english
└── c
└── c.dsl
```
---
The code is not recursive, it does not work with more levels of nesting :sweat_smile:
I added a note that further nesting is not supported. Two levels should cover 99% of use cases.
=> two levels of group names for "Auto group by folder"

src/article_maker.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/589
Fix warnings from https://validator.w3.org/
* use `<meta charset="utf-8">`
* remove useless script `type=text/javascript` https://html.spec.whatwg.org/#the-script-element
* remove a trailing slash on `<link>`
=> Satisfy w3c html validator

redist/org.goldendict.GoldenDict.desktop, src/main.cc
fix https://github.com/goldendict/goldendict/pull/1624#issuecomment-1525586803
macOS' built-in dictionary app can handle `dict://`, a lot of scripts/apps just use it.
By adding this, those scripts will be reusable without trouble.
Install, then `sudo update-desktop-database` -> `xdg-open dict://word`
=> Add `dict://` handler to linux

src/ui/scanpopup.cc
fix: https://forum.freemdict.com/t/topic/11495/2272
The `ui.groupList->getCurrentGroup()` will obtain group's id
The `setCurrentGroup` will loop through groups and compare that id.
* have some groups, open editDictioanries dialog -> add a new group -> close -> scanpoup's group selection isn't changed
* have some groups -> select one -> open editDictioanries -> delete the selected group -> close -> program won't crash, and it will up to Qt decide which one will be selected (not superisingly, the first one :sweat_smile: )
* open editDictiaonries -> delete all groups
* open editDictionaries -> rename group -> still the same one selected even after rename
=> Preserve old group selection after editDictionaries

src/ui/mainwindow.cc, src/ui/mainwindow.hh
This is 5th PR that converts the remaining SIGNAL/SLOT to the new syntax.
They cannot be automatically converted mostly because of type mismatches.
=> Convert navPronounce connect to new syntax

CMakeLists.txt, goldendict.pro, locale/zh_CN.ts, src/common/folding.cc, src/common/folding.hh, src/common/utils.cc, src/dict/dictionary.cc, src/dict/dictionary.hh, src/langcoder.cc, src/ui/groups.cc, src/ui/groups.hh, src/ui/groups.ui, src/ui/groups_widgets.cc, src/ui/groups_widgets.hh, thirdparty/tomlplusplus/toml.hpp, website/docs/manage_groups.md
=> opt: add group by metadata

src/ui/groups_widgets.cc, website/docs/manage_groups.md
https://github.com/xiaoyifang/goldendict-ng/pull/613
I added a few new reviews right before your merge, and it seems you missed them :sweat_smile: 
Anyway, here are the changes: 
```
category = ["chinese",1]
```
In this situation, `elem.as_string()` will lead to a crash because the `1` is not a string. So the code checks the type before as_string.
Also, use get() instead of value/value_or() to avoid a copy.
---
plus some related doc updates
=> Minor fix for auto groups by metadata.toml

goldendict.pro, src/metadata.cc, src/metadata.hh, src/ui/groups_widgets.cc, website/docs/manage_groups.md
The `struct metadata` itself and all its members are defined with `std::optinoal`.
To check their existence, we can just `if(metadata)`/`if(metadata->name)` or `metadata.has_value()`
---
`toml.hpp` is used with discipline to avoid compile time increases: Use it only in `metadata.cc` as an implementation detail and does not include it in `metadata.hh`.
---
`category` is changed to `categories` because a plural seems more natural here:
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies
---
It also includes getting the name from
```
categories = ["1", "2"]
[metadata]
name = "new name"
```
=> `metadata.cc` & `metadata.hh`

src/main.cc
fix: https://github.com/xiaoyifang/goldendict-ng/issues/633
=> fix: other words chopped because url chopping doesn't check condition.

CMakeLists.txt, CMake_Unix.cmake, CMake_Win.cmake
They have almost nothing in common, split win & unix make the build much more cleaner.
The Linux also switched to `thirdparty/eb`, which will generate a `libeb.so` in the output directory.
The linkage is 
```
~/src/goldendict/cmake-build-debug  
> ldd ./goldendict
libeb.so => /home/slbtty/src/goldendict/cmake-build-debug/thirdparty/eb/libeb.so (0x00007f7f7e0df000)
```
As described here 
https://github.com/xiaoyifang/simple-eb/blob/221bc9c831066bf82710be296f28ffaf0ecd360d/CMakeLists.txt#L88
The `libeb.so` will be installed to `/usr/lib/libeb.so`
---
I think we should just mark `eb` as a static library so that we don't need to care about how to install this extra `.so`.
=> CMake: split windows & unix library finding & linking

src/btreeidx.hh, src/common/globalregex.hh, src/dict/aard.cc, src/dict/bgl.cc, src/dict/epwing.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/dict/xdxf2html.cc
related with #657 
fix https://github.com/goldendict/goldendict/issues/1634
This is a workaround (I just comment the workaround in detail 😄 )
Maybe in the future , this whole parse implementation can be replaced with some stream-based-token-process logic
or with a real html parser.
=> fix:startdict parse html incorrect

src/ui/mainwindow.cc, src/ui/mainwindow.hh
=> fix: phrase send from scanpopup should not escape again

src/main.cc
#514   or just remove this argument 
gdMessageHandler only used when enable `--log-to-file`.
which means the `fprintf(stderr, ` will never get chance to run at all.
--------------------
qfile log will cause assert error in multi thread.
"ASSERT: "bytes <= bufferSize" in file C:\Users\qt\work\qt\qtbase\src\corelib\tools\qringbuffer.cpp, line 76"
=> opt: refactor log file write

src/ui/scanpopup.cc
on Ubuntu(Linux),the selection change event occured too often while the delayed time is a little small ,the result is that the popup will show up when users still selecting the text.  Increase the delayed time a little seems can solve this issue.
fix #629
=> fix: selection triggered scanpopup too early

.clang-format, src/main.cc
This is the result on Windows,
If start goldendict from a console ,the console will be used as output.
=> opt: redirect the log to the current console

src/dict/loaddictionaries.cc
My bad, I didn't catch this problem in the review.
`dictMetaData->name` is optional with is similar to a pointer, pointing to a string.
`name->empty()` is std::string::empty.
If name doesn't exist, a`std::bad_optional_access` will be thrown.
Users who previously use metadata.toml that doesn't have the `name` field will be affected.
To reproduce:
create empty `metadata.toml` -> gd still starts (on windows), but without any dicts
```bash
/usr/include/c++/13.1.1/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optional_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_engaged()' failed.
```
=> fix: access optional without checking the existence

src/config.hh, src/dict/sources.cc, src/main.cc
when start goldendict
append the option `--no-tts` will disable the tts loading.
such as 
```
goldendict.exe --no-tts
```
on Windows,  you can append the option to the shortcut of GoldenDict.exe or just start the application in the cmd console.
=> opt: add command line option --no-tts

src/common/globalbroadcaster.hh, src/dict/dictionary.hh, src/dict/mdx.cc, src/dict/zim.cc, src/ftshelpers.cc, src/ftshelpers.hh, src/fulltextsearch.cc, src/fulltextsearch.hh, src/ui/mainwindow.cc
mdx's fulltext creation use the same dictionary object which handle the normal search .
When created the fulltext, `loadArticle` has to be locked by `fulltext` and `normal search`
Which means when creating mdx fulltext ,  the normal search will be affected.
Other dictionaries should face the same dilemma.  In this PR ,  use mdx as an experimental solution.
=> opt: mdx fulltext lock seperated with normal search

src/article_maker.cc, src/article_maker.hh, src/article_netmgr.cc, src/config.cc, src/config.hh, src/ui/articleview.cc, src/ui/articleview.hh, src/ui/mainwindow.cc, src/ui/mainwindow.hh, src/ui/scanpopup.cc, src/ui/scanpopup.hh, src/ui/translatebox.hh
Same thing but with less than half of the code :sweat_smile: 
fix https://github.com/xiaoyifang/goldendict-ng/issues/726
Only 2 cases call `sanitizeInputPhrase`
1. ScanPopup Clipboard
1. Ctrl+V on ArticleView (ArticleView::PasteTriggered)
The old code is passing a phrase::suffix around for this and only this moment.
https://github.com/goldendict/goldendict/commit/60bc05218f0036b361f07e3fc4343103343bd618#diff-2f0f60eeecbf581d1ccc00ea91a53402edc308f7f5210db294df826ec949ae23R483-R484
In old code, when searching via clipboard for words like `Assoc.` results from both `Assoc` and `Assoc.` will show.
If we turn on `ignorePunctuation` by default and get rid of the entire InputPhrase thing,
only the edge case will be changed -> in mainwindow -> Search `Assoc....` will yield both `Assoc` & …
=> Revise how word is getting passed

src/article_maker.cc, src/audiooutput.cc, src/btreeidx.hh, src/common/utils.hh, src/dict/bgl.cc, src/dict/bgl_babylon.cc, src/dict/chinese.cc, src/dict/customtransliteration.cc, src/dict/dictionary.hh, src/dict/dsl.cc, src/dict/epwing_book.hh, src/dict/lingualibre.cc, src/dict/sdict.cc, src/dict/stardict.cc, src/fulltextsearch.hh, src/hotkeywrapper.cc, src/hotkeywrapper.hh, src/langcoder.cc, src/langcoder.hh, src/language.cc, src/macos/machotkeywrapper.mm, src/main.cc, src/ui/about.cc, src/ui/articleview.cc, src/ui/dictionarybar.cc, src/ui/editdictionaries.hh, src/ui/groups_widgets.cc, src/ui/mainwindow.cc, src/ui/preferences.cc, src/ui/scanpopup.cc
This is year 2023, and C/C++ will read every included header and then ignores most lines.
`<QtGUI>` includes every Qt header (a few hundreds) transitively.
This PR removes 3 `<QtGUI>` which are all got introduced before 2010.
(And fix every other header that depends on this "Include *EVERYTHING*" header)
=> clean: avoid include `<QtGUI>`

src/ui/mainwindow.cc, src/ui/mainwindow.hh
* convert its SLOT usage to new syntax (there are only a few old SIGNAL/SLOT to be removed)
* slash a TODO from 2012
Interaction to test: Hold Ctrl or Shift, click a word from dropdown -> open in new tab
=> clean up mainwindow::translateInputFinished 

src/stylesheets/article-style-st-modern.css
Fix the consequence of adding paddings to the body. https://github.com/xiaoyifang/goldendict-ng/pull/650
|Before | After |
| -- | -- |
| ![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/5b30559e-c1c6-421b-b8ee-188d8642c0b9) | ![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/4cc9916e-0b03-4f5d-aa18-1dad10966d45)|
=> fix: modern style's .gddictname

src/ui/scanpopup.cc
regression from https://github.com/xiaoyifang/goldendict-ng/pull/736 due to Input Phase change: if the word is sent to mainwindow, then `definition->getWord()` would be empty
(unrelated: hopefully, the next release would be extremely perfect :sweat_smile: )
=> fix: send to mainwindow got empty word

src/config.cc, src/config.hh
* enable DSL's `alwaysExpandOptionalParts` by default, https://github.com/xiaoyifang/goldendict-ng/issues/733
* extremely rare feature, only dicts that were produced specifically for the original Lingvo probably use this
* enable both wikipedia & wikitionary by default
* disable hotkey for macOS by default (they have troubles in new macOS) https://github.com/xiaoyifang/goldendict-ng/issues/325
* update default websites, remove ones that no long accessible
* add dict.org as default DictD server
dict.org is written in RFC2229 :)
---
Any more ideas?
=> Tweak some defaults

src/common/iconv.cc, src/common/iconv.hh, src/dict/bgl_babylon.cc, src/dict/hunspell.cc
In GoldenDict, the application uses utf-8 as the default encoding. There should be no other use.
=> opt: iconv remove unused parameter

CMakeLists.txt, src/config.cc
Fix the problem of https://github.com/xiaoyifang/goldendict-ng/issues/729#issuecomment-1574896207 reported by @aaly11
The resources path for Linux is hardcoded :sweat_smile: :sweat_smile:
This only affects Linux build 
https://github.com/xiaoyifang/goldendict-ng/blob/87e20912147fe660d458568d3bccbea6836545db/goldendict.pro#L221
=> fix: define PROGRAM_DATA_DIR for cmake

src/article_maker.cc, src/config.cc, src/config.hh, website/docs/topic_userstyle.md, website/mkdocs.yml
close https://github.com/xiaoyifang/goldendict-ng/issues/773 (design)
close https://github.com/xiaoyifang/goldendict-ng/issues/388 (problem fixed)
https://github.com/xiaoyifang/goldendict-ng/issues/806 (related)
Add those lines to `article-script.js` at the config folder will turn on the ultimate dark of the dark reader mode :)
```
DarkReader.enable({
brightness: 100,
contrast: 100,
sepia: 0,
grayscale: 100,
});
```
=> feat: add `article-script.js`

src/dict/mediawiki.cc
=> fix: wikipedia query parameter is incorrect

src/ui/mainwindow.cc
After [this commit](https://github.com/xiaoyifang/goldendict-ng/pull/808/files#diff-56c809abf8615ec9b8833e8e0ddc82d72ff689ed428040d4551b7cb2518b6a0fL630-R628) the global translateLineText doesn't update anymore. For example, when calling `goldendict <search>` from the terminal.
This PR ensures that when setInputLineText is called translateLineText is also updated.
=> fix global translateLineText not being updated 

src/ui/preferences.cc, src/ui/preferences.ui
this feature actually has not take effect .
As the article-style.css has already appointed the font family.
maybe delete this part?
=> opt: use QFontCombox instead

src/dict/dsl.cc
reasons:
1. if the replacement is important ,then the code should not care about the length (size() < 70)
2.  ' ' has been replaced with uC2A0 which is incorrect.  u00A0 is expected.
=> fix: dsl remove too old code logic

src/ftshelpers.cc, src/ftshelpers.hh, src/fulltextsearch.cc
Before:
the searching word must has more than 4 letters.  limited with the original fulltext index engine.
After:
=> fix: fulltext remove query word size check

.github/workflows/macos-homebrew-xapian.yml, .github/workflows/ubuntu-6.2-xapian.yml, .github/workflows/windows-6.x-xapian.yml, src/ui/mainstatusbar.cc
Currently : this crash is only found when used with Qt6.5.1
details check #823 
------
Gussed Reason:
StatusBar's parent widget is MainWindow.
When Mainwindows invoke restoreState()  ,,   somehow the StatusBar's show method got affected and caused an access voilation.
=> fix: possible crash

src/ui/mainwindow.cc, src/ui/mainwindow.hh
Stop the madness of passing `char *` as a function.
Changed code was invented at https://github.com/goldendict/goldendict/pull/482/files which fix ShortCut sometimes doesn't work when focusing on side panels.
Focus one of the side panels, press `Esc` `Alt+D` ......
```
addGlobalAction( &escAction, [ this ]() {
handleEsc();
} );
```
Can be alternatively written as below for C++11
```
addGlobalAction( &escAction, std::bind(&MainWindow::handleEsc, this));
```
which means passing the member function `MainWindow::handleEsc` instanced as `this` to `addGlobalAction`.
`std::bind` is obsoleted by passing lambda with `this` captured after C++14. https://clang.llvm.org/extra/clang-tidy/checks/modernize/avoid-bind.html
Mandatry godblot: https://godbolt.org/z/fx4x7W3jd
=> clean: convert `MainWindow::addGlobalAction` SLOT to new syntax

src/ui/mainwindow.cc, src/ui/scanpopup.cc, src/ui/scanpopup.hh
Small change, to test, -> scanpopup -> right click dictioanryBar -> editDictioanries (if has group, jump to that group's edit page)
* old code has a SIGNAL and a SLOT both named editGroupRequested'
* rename the SIGNAL to editGroupRequest to avoid this ambiguity
=> clean: convert Scanpopup edictGroupRequested to new syntax

src/dict/aard.cc, src/dict/bgl_babylon.cc, src/dict/dictdfiles.cc, src/dict/dictionary.hh, src/dict/dsl.cc, src/dict/gls.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/dict/zim.cc
Obviously, it is a result of copy-paste programming
=> clean: remove duplicated exCantReadFile definitions

src/ui/scanpopup.cc
https://github.com/xiaoyifang/goldendict-ng/issues/880
=> fix: macOS missing slot warning

src/stylesheets/article-style.css
Borrowed from another software, ex_orig should uses a different color
test dict https://gitlab.com/ci-dict/dyu-xdxf/-/blob/main/mandenkan/dict.xdxf by @boydkelly
|Before (left is another software)|After|
|--|--|
|![Screenshot_20230623_135940](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/e65b9bbe-cdd7-435a-ab28-73a21ab7323b)|![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/9a1e2437-c00d-4551-b85f-0160ad0e053f)|
test dict https://github.com/soshial/xdxf_makedict/blob/master/dict_samples/rev34.xml 
|Before|After|
|--|--|
|![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/7a09c116-2909-489b-98e8-aec59da67bcf)|![Screenshot_20230623_143110](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/c6f56fc7-1d56-4bbb-b3bd-7cb55e948356)| …
=> feat: XDXF: distinguish `ex_orig` and `ex_tran`

src/article_maker.cc, src/article_maker.hh, src/dict/aard.cc, src/dict/bgl.cc, src/dict/dictionary.cc, src/dict/dictionary.hh, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/forvo.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/lingualibre.cc, src/dict/mediawiki.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/website.cc, src/dict/xdxf.cc, src/dict/zim.cc
`website.cc` & `mediawiki.cc` is a little bit special: string was converted to QByteArray first which should be unnecessary.
The true purpose is to avoid direct `data` accessing https://github.com/xiaoyifang/goldendict-ng/issues/890
=> clean: unify DataRequest string data appends

src/ui/mainstatusbar.cc
the stacktrace show the line is parentWidget().
avoid using this the parentWidget() method.
or show()?
analysis result.
[1.txt](https://github.com/xiaoyifang/goldendict-ng/files/11926411/1.txt)
=> fix: statusbar crash  at some rare conditions 

src/fulltextsearch.cc, src/fulltextsearch.hh, src/ui/preferences.ui, website/docs/ui_fulltextsearch.md
* rename "Whole word" to "Default"
* add a tooltip explaining what it is "positional info"
* add a note in doc mentioning it is needed for operator NEAR
=> doc: update fts related strings 

src/ui/preferences.cc, src/ui/preferences.ui
fix https://github.com/xiaoyifang/goldendict-ng/pull/916#issuecomment-1616317297
and a layout issue
before:
after:
=> misc fts fix

.github/workflows/macos-homebrew-breakpad.yml, .github/workflows/macos-homebrew.yml, .github/workflows/ubuntu-6.2.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-6.x.yml, .github/workflows/windows.yml
Result: https://github.com/shenlebantongying/goldendict-ng/releases/tag/tag-alpha.6fce7b3c
The download page is too technical, and I have seen people asking which to download multiple times.
The pages contain too many terms that are overwhelming for non-geeks. I don't think any non-geeks care about or have any ideas about those technical details.
I think something like this is better https://github.com/wez/wezterm/releases/tag/20230408-112425-69ae8472
The release date/hashtag/ other details are duplicated with the sidebar.
=> docs: simplify unnecessary tech info in the release page

src/initializing.cc, src/ui/initializing.ui
=> fix: splash windows optimization

src/btreeidx.cc, src/btreeidx.hh, src/dict/stardict.cc
stardict's alts method invoked StardictHeadwordsRequest which called  `dict.findArticles()` as well.  I do not think it is neccessary to called the method twice.
=> opt: limit the number of stardict's extra synonym (from `.syn`) searching

src/dict/dsl_details.cc, src/stylesheets/article-style.css
dsl
```
#NAME "en-zh has BOM"
#INDEX_LANGUAGE "English"
#CONTENTS_LANGUAGE "Chinese"
Zhuang Zhou
庄子 
[m1] ["do","re"] abc[/m]
[m1]Zhuang Zhou[/m]
[m1]庄子[/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
```
sample dsl 
```
#NAME "extra close tag"
#INDEX_LANGUAGE "English"
#CONTENTS_LANGUAGE "Chinese"
Zhuang Zhou
庄子 
[m1] [/abc] abc[/m]
[m1]Zhuang Zhou[/m]
[m1]庄子[/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
[m1] [/m]
```
=> fix: treat unknown dsl tags as text

src/config.hh, src/ui/mainwindow.cc, src/ui/mainwindow.hh
This is pretty much a simplification of https://github.com/xiaoyifang/goldendict-ng/commit/e1b8c323c08033f14b5f83a9e9c75c6109566fc3, which will pop up the notification dialog in the middle of a session, like after 2 hours if the check fails on startup or opening GD for exactly 2 days :sweat_smile: 
close https://github.com/xiaoyifang/goldendict-ng/issues/964
* check 1 time per day on startup and no more
* use github's release api instead of scraping the html page
This api:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release
The api depends on the tag's format. THe tag must starts with `v23.07.16....`
The rate limit for unauthorized users is 60/h which is more than enough.
The data that will be written in the config:
``` …
```
=> rewrite release check

src/common/globalbroadcaster.hh, src/dict/mdx.cc
related with #966
qwebengine browser cache can not work .  the current qt 6 version lacks the neccessary methods to set the response header which will be available until qt6.6.
This PR use qcache and experiment with mdx css file.   
At least this can work on most qt versions.
=> opt: use qcache to hold mdx css file

src/config.cc, src/config.hh, src/ftshelpers.cc, src/fulltextsearch.cc, src/ui/preferences.cc, src/ui/preferences.ui
fix #968
dictionaries 17,cpu 8 cores.
threads 1,time 15   minutes ,   disk cost 1.06GB, cpu consumption 25%
threads 5,time 9    minutes,    disk cost 1.06GB, cpu consumption 60%
result: 
the performance has been improved ,but the improved rate is not linear.  I guess the whole performance is limited by disk write speed.
=> feat: use parallel thread to create the fts

redist/org.xiaoyifang.GoldenDict_NG.metainfo.xml
flatpak need this this:
https://github.com/flathub/flathub/wiki/App-Requirements#appstream
```
> flatpak run org.freedesktop.appstream-glib validate org.xiaoyifang.GoldenDict_NG.metainfo.xml
org.xiaoyifang.GoldenDict_NG.metainfo.xml: FAILED:
• file-invalid          : <screenshot> failed to load [https://xiaoyifang.github.io/goldendict-ng/img/linux_genshin.webp]
• file-invalid          : <screenshot> failed to load [https://xiaoyifang.github.io/goldendict-ng/img/windows_white.webp]
• tag-missing           : <release> required
Validation of files failed
```
Also failed on debian's check.
https://appstream.debian.org/sid/main/issues/goldendict-ng.html
> The value of the <image/> tag is a direct HTTP/HTTPS URL to a screenshot uploaded to a public location on the web. Images should ideally be …
=> fix: use png file for appstream's metainfo.xml

src/audiooutput.cc, src/audiooutput.hh, src/ffmpegaudio.cc, src/ffmpegaudio.hh, src/ui/articleview.cc
choose ffmpeg as audio backend.
then
click the audio link repeatly in wikipedia will cuase the sound to play simultaneously
reproduce steps:
use english wikipedia dictionary.
search laughing ,
=> fix: simultaneous playing sound in wikipedia

CMakeLists.txt, src/version.cc, version.txt.in
This is mostly for packaging systems like deb & rpm, where the `.git/` and `git` do not exist (because they both were designed when tarballs were popular).
=> fix: cmake version.txt generation when built without git

.github/workflows/ubuntu-6.2.yml
Not sure why, but linuxdeploy failed:
```
-- Running input plugin: qt -- 
[qt/stderr] linuxdeploy-plugin-qt version 1-alpha (git commit ID 9a388d3), <local dev build> built on 2023-05-25 23:37:54 UTC
[qt/stdout] Using qmake: /home/runner/work/goldendict-ng/Qt/6.5.2/gcc_64/bin/qmake 
[qt/stdout] 
[qt/stdout] Using Qt version:  6.5.2  ( 6 ) 
[qt/stdout] 
[qt/stdout] Found Qt modules:  
[qt/stdout] Extra Qt modules:  
[qt/stdout] ERROR: Could not find Qt modules to deploy 
ERROR: Failed to run plugin: qt (exit code: 1) 
Error: Process completed with exit code 1.
```
https://github.com/shenlebantongying/goldendict-ng/actions/runs/5705284840/job/15459793333#step:6:414
=> action: use cmake for Qt6 appimage build

src/common/utils.cc, src/common/utils.hh, src/ftshelpers.cc
The total disk-save is about 30% less
=> opt: full text index compact

CMakeLists.txt
related https://github.com/xiaoyifang/goldendict-ng/issues/729
See the review https://bugzilla.redhat.com/show_bug.cgi?id=2213078
close https://github.com/xiaoyifang/goldendict-ng/issues/690
Adding `-DUSE_ALTERNATIVE_NAME=on` that will install different executable name & different icon path & resources folder
The changes are not big, but GD exists too long. Changing those small things will give someone else extra tasks, which should not happen.
I added a note about potential regressions on the top of this flag.
=> feat: CMake: add a flag to parallel install with the original GD (by install files differently)

CMakeLists.txt, icons/programicon.rc
The original cmake build of GD is console application with a console on startup and no icon attached with the executable. This commit makes it a GUI application and add icon.
=> Make appicon work on Windows when built by CMake.

src/stylesheets/article-style-st-classic.css
=> opt: remove outline of dictionary name in classic style

src/common/globalbroadcaster.cc, src/common/globalbroadcaster.hh, src/config.cc, src/config.hh, src/dict/mdx.cc, src/ui/preferences.cc, src/ui/preferences.ui
Add an option to disable possible cache to make dictionary debug easier.
=> feat: add an option to make debug dictionary easier

src/dict/epwing.cc
If epwing dictionary contain >1 subbooks, the following subbook will overwrite the previous index which will cause a "duplicateId" warning and the dictionary can be be queried.
fix #1082
=> fix: epwing dictionary index twice

.github/workflows/macos-homebrew.yml
This is a workaround to Fix #1144
ffmpeg include too much library ,and each update will have the chance to make the dmg does not work .
I intend to disable ffmpeg on Macos ,   
Without ffmpeg ,some speex audio file can not be played.
Users can choose to use external player to bypass this.
=> fix: [macos] disable ffmpeg to solve the #1144 issue

src/main.cc, src/ui/mainwindow.cc, src/ui/mainwindow.hh
show the translation in popup
```
goldendict -s [word]
```
show the translation in main windows
```
goldendict -m [word]
```
Without the above argument, the logic will follow the logic:
if 💡 checked, use popup ,or use mainwindow.
=> opt: add translation windows when invoked from console 

src/stylesheets/article-style.css
=> fix: font missing cause phonetic symbols can not displayed correctly

src/common/file.cc, src/common/file.hh, src/stylesheets/article-style.css
This should avoid copying from QByteArray to std::vector
=> fix: avoid QFile::readall when loading resources 

src/ftshelpers.cc, src/stylesheets/article-style.css
The behaviour of `&QList::front()` is undefined if the size is 0 https://doc.qt.io/qt-6/qlist.html#first
I don't fully understand the context, this may reveal other bugs if the offsets' size is not supposed to be 0.
=> fix: makeFTSIndex crash at startup when indexed articleCount is zero

src/main.cc
Before:
After（disable cache）:
One unexpected benefit:
the memory cache takes effect now.
=> opt: reduce the network stall time

src/stylesheets/article-style.css
Add default font style for phonetic symbols, fix some dictionaries that display phonetic symbols abnormally due to missing style files
=> Add default font style for phonetic symbols

src/article_netmgr.cc, src/dict/mdx.cc, src/resourceschemehandler.cc, src/resourceschemehandler.hh
One benefit of this PR is that ,when changed the mdx's video url to gdvideo:// ,the video can be dragged around.
While the original implementation is not support such feature when the url is gdvideo://.
(it support drag around when the url is file:/// alike).
The only concern is that the video maybe too big .
Test Dictionary
[t.zip](https://github.com/xiaoyifang/goldendict-ng/files/12846133/t.zip)
Search `video`
https://github.com/xiaoyifang/goldendict-ng/assets/105986/784a81d3-1199-4ce9-bd20-b41b351dbc2c
=> opt: experimental changes, resource performance, support gdvideo

src/main.cc, src/ui/mainwindow.cc, website/docs/topic_wayland.md, website/mkdocs.yml
Temporal flag for the time being until alternatives are implemented.
This is very similar to https://github.com/goldendict/goldendict/pull/1548 but in runtime.
https://github.com/xiaoyifang/goldendict-ng/issues/349
The scan popup, which requires things against the grand design of Wayland, will be completely broken.
=> feat: add GOLDENDICT_FORCE_WAYLAND to force wayland (and get things broken)

src/dict/dictserver.cc, src/wordfinder.cc
this is a workaround ,not perfect solution
fix #1262
=> fix: dictserver freeze gui

CMake_Unix.cmake
I was thinking about how would this line in https://github.com/xiaoyifang/goldendict-ng/pull/1369 fixes any problem.
The weird thing is that we already linked against X11
https://github.com/xiaoyifang/goldendict-ng/blob/c15cbbf607d7b13bcbf766835de8d19db35ed7c5/CMake_Unix.cmake#L14-L17
Combined with this comment https://github.com/xiaoyifang/goldendict-ng/pull/1292#issuecomment-1817733658 , I came to realize a stupid mistake I made:
The `FindX11.cmake` will define `X11_LIBRARIES` and `X11_INCLUDE_DIR` but not `X11`
https://cmake.org/cmake/help/latest/module/FindX11.html
The working of ` target_link_libraries(${GOLDENDICT} PRIVATE X11 ` is pure accident because `X11` will be translated into `-lX11` :sweat_smile: 
This PR thanks to @KonstantinDjairo & @Canvis-Me
=> fix: correctly use CMake's FindX11

CMake_Unix.cmake
The GNU libiconv has this thing that rename `iconv_open` to `libiconv_open` when `LIBICONV_PLUG` not defined.
The flag `LIBICONV_PLUG` effectively turns GNU libiconv's header to the base system's iconv header. This might be abuse, but SDL also does this.
https://github.com/libsdl-org/SDL/blob/d6ebbc2fa4abdbe0bd53d0ce8804a492ecb042b9/src/stdlib/SDL_iconv.c#L27-L28
Combined with https://github.com/xiaoyifang/goldendict-ng/pull/1380 should close https://github.com/xiaoyifang/goldendict-ng/pull/1369
Based on the early design doc of FreeBSD's Iconv, it supports a similar dynamic loading mechanism to GNU libconv so encoding supports should not be a problem.
http://citrus.bsdclub.org/
> One can add new locale and encoding without recompiling system libraries by dynamic linking.
=> fix: uses libc iconv on FreeBSD

locale/crowdin.ts, src/config.cc, src/config.hh, src/dict/mediawiki.cc, src/dict/sources.cc
If the base language supports variant conversion, users can set their preferred variant of the language.
=> opt: add the language variant option for wikipedia dictionaries

CMakeLists.txt
`cmake` build complains cannot find `<QPrinter>` in `FreeBSD`
=> Fix cmake complains no <QPrinter>

src/ui/articleview.cc, src/ui/articleview.hh, src/ui/mainwindow.cc, src/ui/scanpopup.cc
This bug is finally fixed
https://bugreports.qt.io/browse/QTBUG-112013
https://github.com/qt/qtwebengine/commit/85bfaa5274b5d47437d6e0634746f70a6646bd4e
This should ultimately eliminate the white flash in dark reader mode.
Related https://github.com/xiaoyifang/goldendict-ng/issues/357
(BTW, I am not sure what you did to reduce white flash previously at https://github.com/xiaoyifang/goldendict-ng/issues/357#issuecomment-1769828055 which does work, but the bug still exists in Qt6.6.2 evidenced by my small demo https://github.com/SourceReviver/qtwebengine_bg_not_work .
Maybe the previous workarounds will be duplicated with this? Or they cover different phases of white flash. I don't know.)
=> fix: reduce darkreader mode white flash further by using QWebEnginePage::setBackgroundColor() (for Qt6.6.3+)

src/ui/maintabwidget.cc, src/ui/maintabwidget.hh, src/ui/mainwindow.cc
The signal `doubleClicked` has been in Qt since Qt5.2
Found during https://github.com/xiaoyifang/goldendict-ng/pull/1418
To test: double click empty space at tabbar -> new tab
=> clean: simplify tabbar double click detect via qt's built-in methods

src/resourceschemehandler.cc
Fix https://forum.freemdict.com/t/topic/11495/3175
The crash related code can also be found at https://github.com/yozhic/GoldenDict-Full-Dark-Theme/blob/54b1cf8b8c744f8aae7479995ce9538d5761ab91/GoldenDict/styles/Dark-Deep/article-style.css#L422-L437
A few lines above  `this->mManager.getResource( url, content_type )`may return `{}`.
Crash stack trace:
=> fix: a crash when qrcx:// fails.

CMakeLists.txt, CMake_Unix.cmake, src/config.cc, src/config.hh, src/dict/loaddictionaries.cc, src/dict/sources.cc, src/dict/sources.hh, src/dict/voiceengines.cc, src/dict/voiceengines.hh, src/main.cc, src/speechclient.cc, src/speechclient.hh, src/texttospeechsource.cc, src/texttospeechsource.hh, src/ui/articleview.cc, src/ui/editdictionaries.cc, src/version.hh
* remove unused WITH_XAPIAN option
* don't link Qt TTS if not requested
Also disable some code that does useless things when Qt TTS is not enabled.
See the comments here: https://github.com/openbsd/ports/blob/971a335e5114e2b952d8f491af87b97c897914d7/textproc/goldendict-ng/Makefile#L55-L63 by @klemensn (sorry for unnecessary troubles.)
=> fix: CMake problems found by the openBSD package

src/gestures.cc, src/gestures.hh, src/ui/articleview.cc, src/ui/mainwindow.cc, src/ui/scanpopup.cc
There were various complaints about the interference between gestures.cc and QtWebEngine's native gestures on macOS.
Someone else disabled gesture.cc on macOS a long time ago https://github.com/xiaoyifang/goldendict-ng/pull/35
This PR removes useless code and disables compilation of gesture.cc on macOS.
Previously, https://github.com/xiaoyifang/goldendict-ng/pull/1407
=> clean: remove macOS unused code related to gestures

src/ui/articleview.cc
fix: https://forum.freemdict.com/t/topic/11495/3118
macOS doesn't consider `/path/a.jpg` as a URL. Only `file:///path/a.jpg` is valid.
---
The parameter of `QDesktopServices::openUrl` is `QUrl`, the old code implicitly converts the path String to QUrl. 
https://github.com/xiaoyifang/goldendict-ng/assets/20123683/fe36ea53-b597-44e7-80e8-0115e1db33ff
=> fix: "Open Image in System Viewer" doesn't work on macOS

src/ffmpegaudio.cc, src/ffmpegaudio.hh
This can prevent crash of https://github.com/xiaoyifang/goldendict-ng/issues/1423
There are 2 problems
* QThread unfinished before creating a new one.
* audioOutput may fail to construct (???? I don't know how yet. `AudioOutputPrivate` seems to have some special internal). 
This works, but I am not sure how to fix this perfectly yet.
---
I think the original code was to spawn multiple audio simultaneously, which makes no sense to humans as nobody can hear mix audios.
So there will be one and only one working audio thread, right?
=> fix: crash when clicking audio insanely fast.

.github/workflows/macos-arm-homebrew.yml, .github/workflows/macos-homebrew.yml
github action failed with:
```
==> git
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.
Subversion interoperability (git-svn) is now in the `git-svn` formula.
Bash completion has been installed to:
/usr/local/etc/bash_completion.d
Error: Process completed with exit code 1.
```
=> fix: macos build

src/ui/articleview.cc, src/ui/articleview.hh, src/ui/mainwindow.cc, src/ui/scanpopup.cc
The original code had to inject `openSearchAction` into `ArticleView` and keep a reference is because the `openSearch` slot was private.
Just connect, rather than inject and connect.
=> clean: remove unnecessary passing of openSearchAction to ArticleView's ctor

src/main.cc
fix: https://github.com/xiaoyifang/goldendict-ng/issues/1267
To test:
```sh
goldendict goldendict://xn--l8j
goldendict goldendict://%CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82
```
Or modify the `Exec` of `/usr/share/applications/io.github.xiaoyifang.goldendict_ng.desktop` to new GD's location -> `sudo update-desktop-database`
Then try
```
gio open goldendict://%CE%BF%E1%BD%90%CE%B5%CF%84%CE%B5%CF%81%CE%B1%CE%BD%CF%8C%CF%82
kde-open goldendict://あ.
xdg-open goldendict://οὐετερανός
or open the url in browser.
```
=> fix: url handler and encoded ACE / Punycode / percent encoded URLs

src/btreeidx.cc, src/btreeidx.hh, src/chunkedstorage.cc, src/chunkedstorage.hh, src/common/file.cc, src/common/file.hh, src/dict/aard.cc, src/dict/bgl.cc, src/dict/dictdfiles.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/gls.cc, src/dict/lsa.cc, src/dict/mdx.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/dict/zim.cc, src/dict/zipsounds.cc
This https://github.com/xiaoyifang/goldendict-ng/pull/1435 , but done right.
I finally understand why the hell there is a `File::Class` when `QFile` already exists and being used.
All existence of File::Class are created for Index files.
It exists because the original authors feel like there is a need to put common staff related to index file process. They didn't explicitly realize this, so only some common code is here and others are duplications scattered around.
=> clean: rename File::Class to what it is really used.

CMakeLists.txt
As discussed in the Debian bug report [2], the current timestamp generation may not be reproducible due to not enforcing the time zone. This patch enforces UTC as time zone information, which will satisfy the reproducible-builds[1] requirement.
[1] https://reproducible-builds.org/
[2] https://bugs.debian.org/1068176
=> CMakeLists.txt: Enforce UTC in timestamp generation

.github/workflows/AutoTag.yml, .github/workflows/Sonar Cloud.yml, .github/workflows/auto format.yml, .github/workflows/cmake build check.yml, .github/workflows/deploy_website.yml, .github/workflows/macos-arm-homebrew.yml, .github/workflows/macos-homebrew-PR-check.yml, .github/workflows/macos-homebrew-breakpad.yml, .github/workflows/macos-homebrew.yml, .github/workflows/ubuntu-6.2.yml, .github/workflows/ubuntu-PR-check.yml, .github/workflows/ubuntu.yml, .github/workflows/windows-6.x.yml, .github/workflows/windows-PR-check.yml, .github/workflows/windows.yml, CMakeLists.txt
Execute the `cpack` directly in builddir or `cmake --build build --target package` and generate both the 7z and nsis installer.
Or use `cpack -G <generator>` to generate other format of packages.
=> CMake: let cpack generate package.

redist/io.github.xiaoyifang.goldendict_ng.desktop
When you pin the app to KDE's Icons-Only Task Manager and launch it, a new icon is created next to the app's icon. I.e. KDE doesn't recognize that the pinned launcher icon and the running app is the same app. 
To fix that in Wayland I had to do this:
1. Run qdbus org.kde.KWin /KWin queryWindowInfo
3. Copy the value from resourceName: goldendict
4. Append it to the .desktop file like this:
```
X-Flatpak=io.github.xiaoyifang.goldendict_ng
StartupWMClass=goldendict <---- HERE
```
The fix should address [this issue](https://github.com/xiaoyifang/goldendict-ng/issues/1467) and probably also [this one](https://github.com/xiaoyifang/goldendict-ng/issues/1160).
=> Add StartupWMClass to the application's ".desktop" file

CMakeLists.txt, CMake_Unix.cmake, redist/mac_info_plist_template_cmake.plist, website/docs/howto/build_from_source.md
This PR encompasses various improvements:
* Makes creating `.dmg` or `.app` locally possible (by removing the need to run macdeployqt, otool, codesign after build)
* Ultimately fix, https://github.com/xiaoyifang/goldendict-ng/issues/814 and fix, https://github.com/xiaoyifang/goldendict-ng/issues/1472
* Rename .app & .dmg so that we may submit to homebrew's cask https://github.com/xiaoyifang/goldendict-ng/issues/1141
And less important ones,
* One more step closer to removing `qmake`
* Remove outdated keys from `.plist` file
* Reduce .dmg size for by switching compression method. (macOS 10.15+)
* ...
Known issue:
The Homebrew Qt and macdeployqt's rpath bug is still not fixed, so we still have to use Qt's installer.
Known alternatives:
CMake's CPack's Drag&Drop generator is 💩💩💩. Lacks basic …
=> feat: utilize CMake for macOS `.app` and `.dmg` creation

src/dict/sounddir.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/1508
related https://github.com/xiaoyifang/goldendict-ng/issues/1417
4 seconds is more than enough unless the soundDir contains 10k-ish folders and obtaining modification time is for some reason slow.
Currently, I don't know how to detect modifications without checking every folder.
Wish we have this to tell that we silently failed https://github.com/xiaoyifang/goldendict-ng/issues/1440
The workaround is just don't have that many folders, put all sound files in one folder.
=> fix: add timeout for sounddir modification scanning for super large sound dir and/or slow filesystem

.github/workflows/macos-homebrew.yml
fix https://github.com/xiaoyifang/goldendict-ng/issues/1510
The minimum possible supported version is bound by Qt -> macOS 11, but it no longer gets updates from Apple.
https://doc.qt.io/qt-6/supported-platforms.html
=> fix: set macOS deployment version to 12.0

src/main.cc, src/stylesheets/qt-lingoes-blue.css, src/ui/mainwindow.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/1506
We cannot do "follow the system" now because it conflicts with the existing qt style sheets.
"popup menu turns black", as shown in https://github.com/xiaoyifang/goldendict-ng/issues/1506#issuecomment-2105654604, is unfixable as of Qt6.7.0
Also, all frames are lost in the new "ModernWindows" when the built-in dark mode is not enabled, but Windows's dark mode is enabled.
=> fix: disable Qt6.7's dark mode and force Fusion style no matter what

redist/io.github.xiaoyifang.goldendict_ng.desktop
amend https://github.com/xiaoyifang/goldendict-ng/pull/1470
xprops shows that
* `WM_CLASS(STRING) = "goldendict-ng", "GoldenDict-ng"` when using `USE_ALTERNATIVE_NAME`.
* `WM_CLASS(STRING) = "goldendict", "GoldenDict-ng"` when not using `USE_ALTERNATIVE_NAME`
=> fix: USE_ALTERNATIVE_NAME + StartupWMClass = No icon

src/ui/mainwindow.cc, src/ui/mainwindow.hh
resolve https://github.com/xiaoyifang/goldendict-ng/issues/1518
Rename the method to what it really is.
Delete legacy & duplications.
The `connect` only happens in `trayIcon`'s init, and thus it will be unique.
=> fix: tray icon <-> toggleMainWindow connected twice

.github/workflows/cmake build check.yml, README.md, website/docs/install.md
This is more of a discussion than changing doc. Motivated by https://github.com/xiaoyifang/goldendict-ng/issues/1523#issuecomment-2143856188
---
First, I propose we change the versioning from `YY.MM.DD` into `YY.MM.Patch` because most people only uses formal releases, and could easily expose problems. Issues like https://github.com/xiaoyifang/goldendict-ng/issues/1506 cannot be easily tested (I simply don't use Windows regularly.) or environment changes like https://github.com/xiaoyifang/goldendict-ng/issues/1523 or simply bump minor qt version. Corrections are needed.
For example, `24.08.0` will be a release and `24.08.1` will be its correction.
---
Minimum supported “Linux” versions are just words, not the actual code. Older Linux and qt versions also work (As of now, qt5 also works). …
=> doc: codify minimum supported OS / versioning / releasing

src/dict/dsl.cc
amend https://github.com/xiaoyifang/goldendict-ng/pull/398
fix https://github.com/xiaoyifang/goldendict-ng/issues/1548
Alternative fix -> https://github.com/xiaoyifang/goldendict-ng/pull/1549
Compared to https://github.com/xiaoyifang/goldendict-ng/pull/1549, this enhances DSL Description by allowing it to use HTML tags.
=> fix: convert DSL description line ends to <br> for HTML display.

CMakeLists.txt
fix https://github.com/xiaoyifang/goldendict-ng/issues/1551
If CI passes, this should work for all Qt6 versions.
=> fix: CMake, qt_add_translations build failure

src/dict/slob.cc, website/docs/dictformats.md
fix #1556 
All slob dicts with raw TeX comes from mw2slob, which already bundles mathjax since a decade ago.
https://github.com/itkach/mw2slob/tree/56da4744af4a6b9099e6bde9bad6cd30ae802226/mwscrape2slob/_MathJax
=> opt: remove mimetex.cgi logic

.github/workflows/windows-6.x.yml, vcpkg.json
with `vcpkg.json` in workspace ,  the vcpkg command will fall to manifest mode.   and git action will throw error.
=> opt: vcpkg manifest error

src/config.hh
I don't think this micro-(optimization or degradation) is needed.
This pack covers a few hundreds of lines, and the subsequent changes are likely unaware it exists.
There is no reason here to change the compiler/platform's default. If there is a reason, why windows-only 😅
=> delete useless MSVC pack pragma in config.hh

src/ui/mainwindow.cc
the method was deprecated when qt>6.5
From the document , the activateWindows() method seems more suitable.
=> opt: remove deprecated method setActiveWindow()

src/ui/articleview.cc, src/ui/articleview.hh, src/ui/mainwindow.cc, src/ui/searchpanel.cc, src/ui/searchpanel.hh
We rely on webengine's findText which will highlight all the matched items on default.
And The highlight feature does not needed and it has not  worked as expected for a little while.
=> opt: Ctrl+F page search remove highlight checkbox

src/dict/dictdfiles.cc, src/dict/gls.cc, src/dict/mdx.cc, src/dict/slob.cc, src/dict/stardict.cc, src/langcoder.cc, src/langcoder.hh, src/ui/groups_widgets.cc, src/ui/orderandprops.cc, website/docs/manage_groups.md
I was just trying to port away from `qt5compat` by porting one single `QRegExp`, and it turns out this feature is implemented wrong in a few places and only partially documented (not only file name, but also dict's canonical name for some formats).
`findIdsForFilename` is just `findIdsForName` plus `QFileInfo::filename`, but every dicts is implemented very differently. Read those code needs to read what is wrapped in `findIdsForFilename` anyway, so I deleted it.
Qt5 CI will fail, how about delete it now 😅
=> feat: revise getting langfrom, langto from dict name or dict file name

src/dict/xdxf.cc, website/docs/dictformats.md
There is a huge number of XDXF dictionaries with "dict.bmp" icon filename (for example: https://booktracker.org/viewtopic.php?p=211743#211743)
=> Update xdxf.cc to support "dict.bmp" icons

src/btreeidx.cc, src/btreeidx.hh, src/headwordsmodel.cc, src/headwordsmodel.hh, src/ui/dictheadwords.cc, src/ui/dictheadwords.hh, src/ui/dictheadwords.ui
This modification based on the assumption that users will not have intention to go through all the headwords  when there are too much of the headwords.
For example, there are 1000 headwords,users may be glad to go through it one by one.
10000 headwords, users may still  have patience to go through it.
1000000 headwords,  users will  retreat from the task.
The modification load the headwords in batch mode.
If users want to check certain words,  users can use filter functionality to meet the goal.
For performance consideration ,  the max returned number of filtered headwords can be set through the UI.
Changes:
when the headwords count < 500000, load all at once.
otherwise load the headwords in batch .
The max returned filtered headwords configuration only available when in batch mode.
=> opt: headwords dialog

src/keyboardstate.cc, src/keyboardstate.hh, src/ui/preferences.cc, src/ui/preferences.hh, src/ui/preferences.ui
I think LeftAlt ,rightAlt ,etc keymodifiers can also be deleted.
These keys added for Windows, but on Windows ,the keys are hidden already.
=> opt: rewrite keymodifier

.github/workflows/release-macos-homebrew.yml
from feedback of community and issue report ,
gd-ng does not run stable on Macos + qt6.7 
add qt 6.6.3 macos release
https://github.com/xiaoyifang/goldendict-ng/issues/1591
=> opt: macos add qt6.6.3 release

CMakeLists.txt, cmake/Deps_Vcpkg.cmake, website/docs/howto/build_from_source.md
Tested manually by inserting a `throw std::runtime_error("whatever")` and GD will create a dmp file successfully.
Unrelated known issues:
+ For some reason, vcpkg can no longer build the Windows version of dump_syms.exe/minidump_stackwalk.exe now. The needed tool has to be obtained from somewhere else.
+ The `-llibbreakpad` here is unneeded: https://github.com/xiaoyifang/goldendict-ng/blob/ddb9203e3425a9762fb1d56666c201adf13cc325/goldendict.pro#L81
=> breakpad support for cmake/vcpkg build

src/delegate.cc
current right to left layout with elidemode and align
Changes based on:
qt must has changed its implementation .
ElideRight in Right to Left Layout will behave exactly like ElideLeft.
After the PR:
=> opt: remove explict RTL elide mode settings of text layout

src/ui/scanpopup.cc
popup pinbutton should only be used to control whether the dialog can be resized.
=> opt: popup focus

.github/workflows/release-macos-homebrew.yml, .github/workflows/release-windows-vcpkg-cmake.yml, .github/workflows/release-windows.yml, CMakeLists.txt, website/docs/howto/build_from_source.md
Sample release: https://github.com/shenlebantongying/goldendict-ng/releases
* `windows-2022` runner
* use PowerShell and avoid bash/cmd
* simply uses `gh release` for packages uploading
* `.7z` & NSIS installer via CPack
* vcpkg utilizes GitHub caches, initial build cost around 35 mins, subsequent builds cost ignorable time
* build time reduced from `qmake+nmake` -> 7.5mins to `cmake+ninja` -> 5mins.
* For some reason, CPack cost super long time to compress the files
=> feat: switch Windows release build to CMake + vcpkg

.github/workflows/PR-check-cmake.yml
Without GitHub caches working, the PR check is too looong https://github.com/xiaoyifang/goldendict-ng/pull/1659#issuecomment-2218583049
Don't have time to fix it in recent time, so let's use winlibs for now :sweat_smile:
(Some work on vcpkg's side is probably needed.)
related doc https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
=> actions: revert windows PR check from vcpkg to winlibs

.github/workflows/create-vcpkg-export-archive.yml
Result: https://github.com/shenlebantongying/goldendict-ng/releases/tag/vcpkg_240711_3d72d8c930e1b6a1b2432b262c61af7d3287dcd0
We don't need to frequently run it (1 time per year seems pretty fine, or when we add new dependencies😅).
---
Use a repo doesn't appear to be practical, because "less than 5 GB is strongly recommended" "you might receive an email from GitHub Support asking you to take corrective action." https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits
The size of `.git` of this repo is already 100Mib+ https://github.com/shenlebantongying/goldendict-ng-vcpkg-export-cache
=> opt: init workflow to create vcpkg package cache and publish it to github relases

src/dict/dsl.cc, src/dict/gls.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/indexedzip.cc, src/indexedzip.hh, src/splitfile.cc, src/splitfile.hh
=> fix: SplitFile thread-safe guard 

.github/workflows/release-windows-vcpkg-cmake.yml, src/ui/mainwindow.cc
During this phase ,the webview has not existed yet
=> opt: do not need to reload webview when initialize dictionaries

src/ui/articleview.cc
When found no results ,the previous highlighted items have not been removed.
=> opt: findtext casesensitivity 

src/dict/stardict.cc
`articleText.toUtf8().data()` has crashed with 
> Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
`articleText.toStdString()`  has not.
Do not know the actual reason .
=> fix: stardict crash

src/common/htmlescape.cc, src/common/htmlescape.hh, src/dict/stardict.cc
the stardict qstring part has caused crash sometimes.
Fix #1702
basic rule: avoid unnecessary conversions between QString and string 
Changes:
1.
```
QString newTag   = QString::fromUtf8(
( addAudioLink( href, getId() ) + "<span class=\"sdict_h_wav\"><a href=" + href + ">" ).c_str() );
```
to 
string only.
2. `return (articleText.toUtf8.data());`
to
```
auto text = articleText.toUtf8();
return text.data();
```
3. 
`QString stripHtml( const QString & tmp )`
to
`QString stripHtml( QString tmp )`
=> fix: stardict qstring modification

src/main.cc, src/unix/ksignalhandler.cc, src/unix/ksignalhandler.hh
This should fix
- https://github.com/xiaoyifang/goldendict-ng/issues/1375
- https://github.com/xiaoyifang/goldendict-ng/issues/1531
- https://github.com/xiaoyifang/goldendict-ng/issues/1532
=> feat: properly handle Unix signals, like `SIGTERM`, for graceful exit

.editorconfig, .gitattributes, .gitignore
Pretty annoying, tools on Windows randomly change line endings to 💩.
`.editorconfig` is mostly for VS2017+ and various other https://editorconfig.org/#pre-installed
`.gitattributes` is for git (the git for windows convert CLRF by default? No idea and don't care, this will override it.)
=> dev: ensure line ending is always LF

.clang-tidy
Fix
* The missing comma at the head doesn't exclude many warnings
* The comment in middle doesn't exclude warnings in the following lines
Thankfully, both leads to more warnings instead of reducing 😅 
* Remove `deprecated-headers` warnings -> Couldn't matter less.
* Remove C-style cast & reinterpret_cast warnings
* We only use them in a few places to interact with external APIs
* The warnings are conflicting, convert C-style cast will warn reinterpret_cast is wrong or const_cast is wrong.
* There is noway to satisfy clang-tidy.
* Remove `cppcoreguidelines-pro-bounds-array-to-pointer-decay`
* A pain of C style array, but it is not obvious what to fix when interacting with C libraries
* just avoid them altogether is better -> `cppcoreguidelines-avoid-c-arrays`
* Add a few more
* Sort
=> dev: update .clang-tidy

src/dict/slob.cc
Amend https://github.com/xiaoyifang/goldendict-ng/pull/398
After
=> fix: slob format's description HTML display

CMakeLists.txt, src/common/iconv.cc, src/common/iconv.hh, src/dict/slob.cc
Another attempt to remove usage of `Core5Compat`.
Is this change correct?
The Qt5 version of `QTextCodec::codecForName` underneath uses ICU
GNU libiconv has a large table of encoding alias
https://git.savannah.gnu.org/gitweb/?p=libiconv.git;a=blob;f=lib/encodings.def;h=e5063d329886818033e6d3aa14618c75d8b07852;hb=HEAD#l441
ICU also has a big table of encoding alias 
https://github.com/unicode-org/icu/blob/1414e80f6c1376afa65eb388aaaafb53169fc3dc/icu4c/source/data/mappings/convrtrs.txt#L891
Both includes names from various sources like INNA, glibc, java, windows, so I assume `QTextCodec::codecForName` and `iconv_open` are equal.
unrelated
---
`QStringConverter` since Qt6.5 also uses ICU to support equal set of encodings like old QTextCodec btw.
Maybe the correct path forward is just use ICU …
=> clean: port away from `QTextCodec` in `slob.cc` and clean up iconv

.git-blame-ignore-revs, src/article_maker.cc, src/btreeidx.cc, src/btreeidx.hh, src/common/wstring_qt.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/epwing_book.cc, src/dict/hunspell.cc, src/dict/slob.cc, src/dict/voiceengines.cc, src/ftshelpers.cc, src/instances.cc, src/langcoder.cc, src/speechclient.cc, src/splitfile.cc, src/ui/groups_widgets.cc, src/ui/orderandprops.cc, src/zipfile.cc
These 2 types are just alias in Qt6.
* `Qt5/QList` is removed, and `Qt6/QList` is actually `Qt5/QVector`. (Mostly because the use case of `Qt5/QList` doesn't exist, and it is slow.)
* Pretty sure this is the dude who pushed the removal `Qt5/Qlist` (it only takes a decade 😅)
* https://marcmutz.wordpress.com/2010/07/29/sneak-preview-qlist-considered-harmful/
* `QPair` is deleted.
* Unrelated to this PR, but various style guides simply ban/discourage "Pair" https://google.github.io/styleguide/cppguide.html#Structs_vs._Tuples
=> clean: replace removed `Qt5/QList` and `QPair`

.github/workflows/release-macos-homebrew.yml
For 2 reasons
* Nobody else has macOS hardware → hard to figure out macOS only issues.
* macOS has a top-notch crash handler built into the system that supports C++ very well. Let's just use it.
Both Qt & Homebrew strips debug symbols, so only symbols from goldendict's main executable are included.
The size of "goldendict" executable increases merely from 5.8Mb to 6.2Mb on my machine.
=> dev: ship macOS version with debuginfo

src/dict/dictionary.cc, src/dict/dictionary.hh, src/ui/dictionarybar.cc, src/ui/dictionarybar.hh, src/ui/mainwindow.cc, src/ui/scanpopup.cc
some of the code added to prevent crashes had a bad side effect, causing the icons to get a bad quality.
two line of codes in two different files were causing that downscaling, the first line was removed, the second had its value changed to a higher value, both conditions were tested and the result is pretty good:
=> feature: High-quality dictionary icons in toolbar

src/dict/dictionary.cc, src/dict/dictionary.hh, src/ui/dictionarybar.cc
@KonstantinDjairo I think this will fix the problem now.
For high density screens, more pixels are needed for the same logical size.
amend https://github.com/xiaoyifang/goldendict-ng/pull/1750
=> fix: consider devicePixelRatio when scaling icons

cmake/Deps_Unix.cmake
I did notice that the macOS installers are smaller since a few days ago[^1]. I didn't know why, and now we know 😅.
The `libicudata.74.dylib` is missing, but thankfully the other two parts, `libicui18n.74.dylib` and `libicuuc.74.dylib`, does present in the app bundle.
This means that the macdeployqt and other underlying things are working, but just don't consider libicudata as dependency.
So, let's just depends on ICU explicitly to help them.
Tested with https://github.com/shenlebantongying/goldendict-ng/releases/tag/v24.05.13-alpha.dc45837f
related https://github.com/xiaoyifang/goldendict-ng/issues/1761
[^1]: The problem starts from -> https://github.com/xiaoyifang/goldendict-ng/releases/tag/v24.05.13-alpha.22b1c043 (Coincidently, I made …
=> fix: ensure icu4c are copied to app bundle on macOS

website/docs/howto/build_from_source.md
it's important for the user to have both options of build, and the first one being the simplest and with less dependencies
=> doc: clarify that ninja is optional and add other potential useful flags for CMake build (#1768)

.github/workflows/release-AutoTag.yml, .github/workflows/release-macos-homebrew.yml, .github/workflows/release-windows-vcpkg-cmake.yml, CMakeLists.txt
As we previously discussed, now we are versioning like Ubuntu. https://github.com/xiaoyifang/goldendict-ng/pull/1543
Also, I think we should stop using obnoxious codename suffix, lets it be a stable suffix “Release”.
In case you want another code name, we can just change the title. I don't think we have to cost time to automate it, since release isn't often, manually edit it is fine.
close https://github.com/xiaoyifang/goldendict-ng/issues/1744
=> dev: prepare a new version

src/common/wstring.hh
I read it, and it provides no value at all. Nobody else should read it again.
We live in a better world now. The problems that the original GD's author was facing are no longer.
For the 4th paragraph about performance, I don't totally agree. (e.g., Temporally converting string to UTF-32 will involves at least one converting + allocation + copying, there could be no performance gains depending on situations.)
=> clean: delete wall of text in `wstring.hh`

src/dict/aard.cc, src/dict/bgl.cc, src/dict/dictdfiles.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/gls.cc, src/dict/lsa.cc, src/dict/mdx.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/dict/zim.cc, src/dict/zipsounds.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/1576
This PR does absolutely nothing technically, because removing these packing compiler directives is OK 😅😅😅.
In both 32 & 64 bits machines, a `struct` with all 32bit fields will be already “packed” (This doesn't appear to be in the standard, but it is what all 3 major compilers do).
However, this PR makes code's purpose clear (Not really, because only after reading the code, one would know that GD is using this trick to read/write multiple fields at once) and reduce inconsistency (It is pretty weird to see the inconsistency as showed in https://github.com/xiaoyifang/goldendict-ng/issues/1576.).
---
This PR also removes gcc and clang's `__attribute__((packed))__` because they both of them supports `#pragma pack(push, 1) -> #pragma …
=> clean: mark all `Idxheader` packed explicitly

.github/workflows/PR-check-cmake.yml, .github/workflows/release-macos-homebrew.yml
Probably needs to drop macos-12 support.
Homebrew stops supporting it.
Once the packages are updated ("old bottles are removed from homebrew's serve?"), older mac have to build from source.
This takes forever to finish:
https://github.com/xiaoyifang/goldendict-ng/actions/runs/11113891897/job/30879229991?pr=1792
=> actions: bump `runs-on` to macos-13 because homebrew no longer supports macos-12

src/config.cc
fix https://github.com/xiaoyifang/goldendict-ng/pull/1789#discussion_r1780651552
=> fix: init icon size is not normal due to missing null check

src/config.cc, src/config.hh, src/ui/dictinfo.cc, src/ui/dictinfo.hh, src/ui/dictinfo.ui, src/ui/dictionarybar.cc, src/ui/dictionarybar.hh, src/ui/mainwindow.cc, src/ui/mainwindow.hh, src/ui/scanpopup.cc
There are a few mentions on internet about `editDictionaryCommandLine`.
But what's the point? If a user wants to edit DSL/XDXF files directly, then just open it with an editor, there is little to no reason to open it via GD and waste time to discover this thing.
It is not fully implemented anyway (if it doesn't work, user cannot know why it doesn't work).
To enable it, user have to edit `config`'s `editDictionaryCommandLine` with `${editor name} %GDDICT%`. This is impossible to be discovered.
=> clean: purge undocumented and useless `editDictionaryCommandLine` 

.clang-tidy, src/dict/dsl_details.cc
Porting away `QTextCodec` for DSL format needs to reimplement an encoding guessing based on BOM `QTextCodec::codecForUtfText`.
However, `QStringConverter` has an enhanced version of the same function that also covers the case of "guessing based on the first char".
A test file with & without BOM https://github.com/xiaoyifang/goldendict-ng/files/11645150/dsl_sample.zip
Plus general code improvement to related code.
=> clean: port DSL encoding guessing away from QTextCodec

src/dict/dictdfiles.cc
Amend https://github.com/xiaoyifang/goldendict-ng/pull/398
After
Before
=> fix: dictd's description display (00databaseinfo)

src/dict/dictionary.cc, src/ui/articleview.cc
Fix 2 deprecation notices as in https://github.com/xiaoyifang/goldendict-ng/actions/runs/11204695739/job/31143387827
* It appears that QVariant's type system got replaced by something more powerful https://www.qt.io/blog/whats-new-in-qmetatype-qvariant
* QByteArrayView, similar reasons for using std::string_view
=> clean: minor deprecation fixes

src/ui/scanpopup.cc
This fixes https://github.com/xiaoyifang/goldendict-ng/issues/1803 and also works for Linux.
The root issue is that the behavior of `Qt::Popup` is underspecified, complex and may evolve overtime.
---
Someone else did notice a similar issue on Linux, but whatever he concluded is :hankey:.
* https://github.com/goldendict/goldendict/commit/15dfdee49ff0400f22903c621562d89ca604f983
* https://github.com/goldendict/goldendict/issues/645
=> fix: set scanPopup flags to what's is needed instead of Qt::Popup

CMakeLists.txt, src/macos/machotkeywrapper.mm
Related https://github.com/xiaoyifang/goldendict-ng/issues/325
Tell user what's wrong, and what to do :)
Auxiliary changes
* Document how Cmd+C+C is implemented.
* Build the `.mm` file as Objective-C++17.
* Surprisingly, despite the file is named `.mm`, it doesn't use Obj-C feature, and it was getting compiled as C++ file (https://cmake.org/cmake/help/latest/release/3.16.html#languages)?
* Anyway, I am going to turn it on to make life easier.
Demo:
https://github.com/user-attachments/assets/d794250e-30d5-47db-853f-7645a329f152
=> feat: macOS, check and request Accessibility permission for Cmd+C

src/langcoder.cc, src/langcoder.hh, src/ui/mainwindow.cc, src/ui/mainwindow.hh
* `MainWindow::fillWordListFromHistor` is staff from Qt3 era -> https://github.com/goldendict/goldendict/commit/54bba79c60aacdac451f55ec384f1fede15d7f0b Unused (even in the original GD).
* `LangCoder::icon` leftover of https://github.com/xiaoyifang/goldendict-ng/issues/537
=> clean: delete `MainWindow::fillWordListFromHistory` and  `LangCoder::icon`

src/config.cc, src/config.hh
close https://github.com/xiaoyifang/goldendict-ng/issues/1375
The QTimer has almost no impact on CPU/power usages https://github.com/xiaoyifang/goldendict-ng/issues/1375#issuecomment-2403922311
=> feat: set the default history and favorite saving interval to 15 minutes

src/history.cc, src/history.hh, src/ui/mainwindow.cc
Follow up of https://github.com/xiaoyifang/goldendict-ng/pull/1814 https://github.com/xiaoyifang/goldendict-ng/pull/1813, improvements after reading this file.
* delete `groupID` related code which is unused since the original GD and I don't see potential use of it.
* delete unused history constructor
* delete 💩 -->`Load` An empty struct to distinguish constructor against the unused one
* shorten file reading/saving
* restore rejecting super long entry
* https://github.com/xiaoyifang/goldendict-ng/pull/1224/files#diff-21e1b1b3fdeeaf0f25fde71b5321f41ec40a2cbe2b48cbe22a0d7884e964a24aL72
=> clean: delete or rewrite weird things in `history.cc`

.github/workflows/PR-check-cmake.yml, src/ui/mainwindow.cc
The root issue is 
```cpp
connect( ui.searchInPageAction, &QAction::triggered, this, [ this, view ]() {
```
The 3rd `this` is mainwinidow, while the`connect` is only valid during the current `view`.
fix https://forum.freemdict.com/t/topic/11495/3513
The workaround for scanpopup is not invalidated by this PR.
=> fix: ctrl+F crashes when last tab is closed

src/dict/programs.cc
This is only a problem for windows. 
And the main issue is that people now usually don't care about whatever the hell is local 8 bit and code pages, and proceed to assume input and output are UTF-8.
Assuming UTF8 is the correct choice.
Sample issue https://forum.freemdict.com/t/topic/32765
Follow up and a mini survey of the issue https://github.com/xiaoyifang/goldendict-ng/pull/1743#issue-2503673868
=> feat: decode program dicts as UTF-8 instead of local8bit

.github/workflows/PR-check-cmake.yml
Add a rolling release distro to test issues from very new versions of dependencies.
---
The container used is maintained by "official" Arch Linux team
https://gitlab.archlinux.org/archlinux/archlinux-docker
I choose the one hosted on `ghcr` aka GitHub container registry with tag `base-devel`
https://github.com/archlinux/archlinux-docker/pkgs/container/archlinux
Related github doc https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container
=> actions: add Archlinux pull request check

src/dict/loaddictionaries.cc, src/dict/loaddictionaries.hh, src/initializing.cc, src/initializing.hh, src/ui/editdictionaries.cc, src/ui/mainwindow.cc
Amend https://github.com/xiaoyifang/goldendict-ng/commit/9ae4e57bb8f9ec4625350a2e419444e9752b757e
I honestly cannot tell the difference without the code.
=> clean: simplify loadDictionaries & Initializing dialog's `showInitialy` parameter

src/ui/about.ui, src/ui/authentication.ui, src/ui/dictgroupwidget.ui, src/ui/dictheadwords.ui, src/ui/dictinfo.ui, src/ui/editdictionaries.ui, src/ui/fulltextsearch.ui, src/ui/groups.ui, src/ui/initializing.ui, src/ui/mainwindow.ui, src/ui/orderandprops.ui, src/ui/preferences.ui, src/ui/scanpopup.ui, src/ui/sources.ui, src/ui/texttospeechsource.ui
I was editing the `.ui` files a moment ago, and resaving them will bring those Qt6's enum namespace changes.
Open and resave all to avoid troubles.
=> clean: open and resave all `.ui` files to adapt Qt6 Designer's enum changes

.github/workflows/Release-all.yml
amend https://github.com/xiaoyifang/goldendict-ng/pull/1836
Bash's HEREDOC needs quote to be a block of string literal -> https://www.gnu.org/software/bash/manual/bash.html#Here-Documents
=> fix change log generation again

src/ui/about.ui, src/ui/authentication.ui, src/ui/dictgroupwidget.ui, src/ui/dictheadwords.ui, src/ui/dictinfo.ui, src/ui/editdictionaries.ui, src/ui/fulltextsearch.ui, src/ui/groups.ui, src/ui/initializing.ui, src/ui/mainwindow.ui, src/ui/orderandprops.ui, src/ui/preferences.ui, src/ui/scanpopup.ui, src/ui/sources.ui, src/ui/texttospeechsource.ui
Reverts xiaoyifang/goldendict-ng#1834
Qt back ported scoped enums all the way back to Qt5.15.18+, Qt6.5.4+, Qt6.2.13+ (These versions will eventually available to open source uses, but not today).
Very random, but here is Qt5.15.12 😅  https://github.com/qt/qt5/tree/v5.15.15-lts-lgpl
Qt Designer of Qt6.7 is currently utterly broken (save will introduce these changes which breaks older version 💩💩💩).
=> fix: Revert "clean: open and resave all `.ui` files to adapt Qt6 Designer's enum changes"

src/article_netmgr.cc, src/dict/dsl.cc, src/dict/xdxf2html.cc, src/ui/articleview.cc
=> opt: remove audio search logic in the current group

src/config.cc, src/dict/sources.cc
I'm using `GoldenDict-ng-24.09.0-Qt6.6.3` and found that in portable mode the *content* folder is not added initially, and once added it is not portable at all, the path is saved as an absolute path in the *portable/config* file, so it cannot be used on my other PC.
#1320 is relevant but some code is missing in the latest source. Here is the solution. The portable *content* folder should be relative and not stored in the *portable/config* file, and I make the path always the first in the list and make it uneditable.
Finally, I bring it back as #1394 and fixed some corner cases.
=> fix: default `content` directory in portable mode

src/article_netmgr.hh, src/dict/forvo.cc, src/dict/lingualibre.cc, src/ui/articleview.hh
It seems newer version of clang has this warning enabled by default and the build log full of this thing.
https://github.com/xiaoyifang/goldendict-ng/actions/runs/11622770897/job/32368748936
clang-tidy doesn't appear to be able to catch all cases https://github.com/xiaoyifang/goldendict-ng/pull/293
=> clean: add `override` to satisfy clang's `Winconsistent-missing-override`

.git-blame-ignore-revs, src/article_maker.hh, src/audioplayerinterface.hh, src/common/base_type.hh, src/common/wstring.hh, src/config.hh, src/dict/bgl_babylon.hh, src/dict/epwing_book.hh, src/dict/forvo.cc, src/dict/lingualibre.cc, src/dict/mdictparser.hh, src/dict/mediawiki.cc, src/dict/slob.cc, src/hotkeywrapper.cc, src/hotkeywrapper.hh, src/language.hh, src/multimediaaudioplayer.cc, src/wordfinder.hh
I feel `using` is a straight upgrade of `typedef` especially for long type names.
There is only 2 `typedef` left because that file is currently compiled as C.
=> clean: apply clang-tidy's `modernize-use-using` (replace most `typedef`)

src/ui/groups_widgets.cc, src/ui/groups_widgets.hh
=> fix: remove some tabText() in groupWidget when rename group

src/gestures.cc, src/ui/scanpopup.cc, src/ui/scanpopup.hh
Half of the remaining default compiler warnings are this thing.
Pretty much direct renames.
=> clean: fix all `globalPosition` deprecations to stop related warnings

src/config.cc, src/config.hh
A very interesting deprecation from Qt's side.
In Qt5 
```
QKeySequence[]-> int`
```
In Qt6
```
QKeySequence[]-> QKeyCombination::operator int() -> int`
^ deprecated
```
---
Anyway, the original GD's author's question finally got an answer in Qt6 :sweat_smile:
=> clean: deprecated `QKeySequence[]->int`; answer ikm's question from 2009

CMakeLists.txt
close https://github.com/xiaoyifang/goldendict-ng/issues/1917
depends on https://github.com/xiaoyifang/goldendict-ng/pull/1916
method is use `qt.conf` to set a `QLibraryInfo::path( QLibraryInfo::TranslationsPath )`
This adds 7Mb "bloat" 😅
=> fix: deploy qt translations for macOS

CMakeLists.txt, src/macos/macmouseover.mm, website/docs/install.md
Depends on https://github.com/xiaoyifang/goldendict-ng/pull/1920
The remaining ones aren't really fixable --> some are Qt6.7/6.8 features.
And, we need to support Qt6.4.
---
So, let's disable ~~Qt≤6.5~~ Qt≤6.7 deprecated features.
Using them will cause build error.
Sample failure --> https://github.com/xiaoyifang/goldendict-ng/actions/runs/11718114232/job/32638882331?pr=1921#step:6:300
Then disable warnings from Qt's side.
=> opt: disable Qt≤6.7 deprecated features and disable Qt deprecation warnings

src/config.cc
https://github.com/xiaoyifang/goldendict-ng/pull/1912
key2 have to be not equal to both to be valid.
=> fix a mistake of #1912

src/ui/editdictionaries.cc
=> opt: dictionary tab switch will show blank widget when source changing.

.clang-tidy, src/dict/mdictparser.cc, src/dict/utils/decompress.cc, src/dict/utils/decompress.hh
close https://github.com/xiaoyifang/goldendict-ng/issues/1775
Micro optimization, remove one extra data traversing to calculate the hash.
Adler-32 is a rolling hash calculated together with the inflating process.
Fix various small issues
* move `using` out of the header (it propagates into all headers that include it)
* create buf only when it will be used (`inflateInit == Z_OK`)
* check `inflateEnd`'s return value
=> opt: mdx -> avoid duplicated Adler-32 checksum in zlib decompression

src/ui/mainwindow.cc, src/ui/mainwindow.hh
fix https://github.com/xiaoyifang/goldendict-ng/issues/1323
Note that this focus stealing exists for a decade. Honestly cannot tell if it is a feature or misdesign 😅 
As of now, I think it is a misdesign, because the dialog is a tall narrow window, it don't cover the article display area (probably only because today's computer monitor is larger than a decade ago).
https://github.com/xiaoyifang/goldendict-ng/commit/46298a842cead991e271535105db546f80f88eba#diff-5672b26c3952a17c577362e80c313b2d937da7cdf2d4e4a91bba90e68ed855ccR3513
Related change
* Move `headwordReceived` into lambda, because it only serves the head word dialog.
* Stop the confusing `toggle****` and `showOnly` thing
=> opt: don't focus on the main window if word comes from headword dialog

src/config.cc, src/config.hh, src/ui/mainwindow.cc, src/ui/preferences.cc
* implement https://github.com/goldendict/goldendict/issues/1356#issuecomment-1362735547
* close https://github.com/xiaoyifang/goldendict-ng/issues/857
* close https://github.com/xiaoyifang/goldendict-ng/issues/583
* related https://github.com/xiaoyifang/goldendict-ng/issues/1731
* fix a bug that clicking the tray icon on macOS will bring up both "the tray menu" and the "main window" up (The tray menu showing up is macOS's intrinsic behavior? We don't have any code touches it).
---
After this change:
The toggle clipboard monitoring is moved to the dock menu.
To toggling visibility using dock icon: "Click" to bring up and "Option+Click" to hide. Note that "Option+click" may also hide other staffs, a weird shortcut.
---
Pretty sure this will break someone's habit, however
* The tray icon …
=> fix: macOS -> replace the tray icon with a dock menu

.clang-tidy, src/common/ex.hh
=> refactor: change `DEF_EX` macro's underlying implementation to template

src/dict/aard.cc, src/dict/bgl.cc, src/dict/gls.cc, src/dict/stardict.cc, src/dict/xdxf.cc
After https://github.com/xiaoyifang/goldendict-ng/pull/1939, unused warning will show up :)
=> clean: remove unused `DEF_EX`

src/macos/machotkeywrapper.mm
Let's merge this in another day,
Chop related code to half.
---
This region of code looked scary because the first line assumes everyone uses English keyboard.
```
TISInputSourceRef inputSourceRef = TISCopyInputSourceForLanguage(CFSTR("en"));
```
So, the next line patches it to copy current input source -> TISCopyCurrentKeyboardInputSource
But japanese keyboard is slightly different, so it got patched again TISCopyCurrentKeyboardLayoutInputSource
Just uses the last one `TISCopyCurrentKeyboardLayoutInputSource`, all code are no longer needed.
---
Also change mappping to a vector instead of `calloc`.
=> clean: simplify macOS hotkey mapping code

.git-blame-ignore-revs, src/article_maker.cc, src/common/iconv.cc, src/common/wstring_qt.cc, src/common/wstring_qt.hh, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/epwing_book.cc, src/dict/hunspell.cc, src/dict/mdx.cc, src/dict/mediawiki.cc, src/dict/programs.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/utils/indexedzip.cc, src/dict/xdxf.cc, src/dict/xdxf2html.cc, src/ui/articleview.cc, src/wordfinder.cc
The reason there is such function was because the Windows version of gd::wstring is whatever we don't care anymore.
https://github.com/timonwong/goldendict/commit/babde3d53d21f8ba2a13c41d0cf2f391e6839094#diff-426cee2bb29733a476f42c3ba97c2ebc90647d51f30d6feb74b5fee3d15976b4R4-R32
Let's just use the real thing.
=> clean: remove redundant gd::toWString

src/dict/dictserver.cc
Crash site:
`reply` is `wn "`.
A combination of 2 factors:
Original GD's code assumes `"` `"`  is a pair, and access the string by index.
New code doesn't wait for response to ready.
---
It for some reason reliably crash for me when searching "get" and always end with a incomplete `wn "`. I thought it is just out of bound access, but looking into the website reveals that three are a few more words aren't arrived. It always reaches `gettable`. (Does this mean dict.org is hosted on a single machine and my latency to this machine is a constant and thus it always crash at that point 😅 )
=> fix: a DICT crash caused by string out of bound access

website/README.md, website/docs/custom_dictionary.md, website/docs/manage_sources.md, website/docs/topic_userstyle.md, website/docs/ui_shortcuts.md, website/docs/ui_toolbar.md, website/mkdocs.yml
Document these hidden features:
* `[!abc]` wildcard syntax https://github.com/goldendict/goldendict/commit/ade20fc1bf22e9942e62c27371de9d68cc70e96a#diff-fd6b000fff2f92c847e6f5b997d1eae57bd792f9f747b4dcb5a3bdc0464bbc35L75
* `fts=true` https://github.com/xiaoyifang/goldendict-ng/pull/1730
* `article-style-print.css` https://github.com/xiaoyifang/goldendict-ng/commit/21b2d3b747aa8136bf15ac12f2f8afe8f0b90d34#diff-76602be0b8dbf09757c540e3b4c474b477cac3bdf38ca318e6284cb34020cd2eR756
---
Others
* move solo mode doc to `toolbar & dictionary bar` page
* misc...
=> doc: various updates Nov 2024

src/audio/audiooutput.cc, src/audio/ffmpegaudio.cc, src/audio/ffmpegaudio.hh, src/audio/multimediaaudioplayer.cc, src/audio/multimediaaudioplayer.hh, src/common/gddebug.cc, src/common/wildcard.cc, src/dict/dsl_details.hh, src/dict/epwing_book.cc, src/dict/epwing_book.hh, src/dict/gls.cc, src/dict/mdictparser.cc, src/dict/sdict.cc, src/dict/utils/indexedzip.cc, src/iframeschemehandler.cc, src/main.cc, src/ui/article_inspect.cc, src/ui/articleview.cc, src/ui/dictheadwords.cc, src/ui/mainwindow.cc, src/ui/scanpopup.cc, src/ui/scanpopup.hh
I was just wanted to delete Qt5 branch code, but found Qt6≤3 branches aren't really useful either.
The `hotkeywarpper.cc/hh` aren't touched because I am not on windows/Linux as of now.
Plus minor `#include` cleanup.
=> clean: delete most Qt5 & <=6.3 conditional compiled code (`QT_VERSION_CHECK` macro)

src/hotkeywrapper.cc
fix https://github.com/xiaoyifang/goldendict-ng/issues/1938
Fix these Win/Meta related issues from the original GD.
fix https://github.com/goldendict/goldendict/issues/1185
fix https://github.com/goldendict/goldendict/issues/1211
Not sure how things used to work, but as today:
* Qt uses `Qt::KeypadModifier` to know if pressed numbers belongs to Numpad.
* The original code from 2009 for some reason maps them to `VK_NUMPAD`
For Win/Meta, only the left one --> LWIN is supported.
=> fix: windows global hotkey Win/Meta and 1-9 doesn't work

src/hotkeywrapper.cc, src/hotkeywrapper.hh, src/windows/winhotkeywrapper.cc
Plus small adjustments that have no semantic changes.
---
Why?
Google `#ifdef Hell`😅
=> refactor: move most of the Windows specific code out of `hotkeywrapper.cc`

src/config.hh, src/dict/btreeidx.hh, src/dict/xdxf2html.cc, src/hotkeywrapper.hh, src/main.cc, src/ui/favoritespanewidget.hh, src/ui/historypanewidget.hh
It appears that the Visual Studio's Analyze → Run code analyze button is just rebuilding the project, then collect warnings.
Edit: Actually, I don't know what's the rule it follows. It seems CMake (?) project cannot configure it as written in VS's doc. The panel is blank for me.
https://learn.microsoft.com/en-us/cpp/code-quality/quick-start-code-analysis-for-c-cpp?view=msvc-170
This fixes all the default warnings.
Mostly uninitialized variables. Initialize everything religiously.
=> clean: fix some issues found by the code analysis of Visual Studio

.github/workflows/PR-check-cmake.yml, src/audio/audioplayerfactory.cc, src/audio/audioplayerfactory.hh, src/audio/internalplayerbackend.cc, src/audio/internalplayerbackend.hh, src/config.cc, src/config.hh, src/ui/mainwindow.cc, src/ui/preferences.cc
I think this is a good time to switch default to Qt multimedia.
Then I find this weird warning. Why the hell changing the default require changing more code? 
https://github.com/xiaoyifang/goldendict-ng/blob/c7d0feb2e8d237f21365da2a7a1e56f0a6e7e78d/src/audio/audioplayerfactory.cc#L52-L54
Then I found this unusual thing in the middle of config.
It is called as "backend" and can be acts as "backend", but it doesn't work as a "backend" (because it invokes other backends).
Anyway, let's move it out from the big config.cc.
`git blame` is not useful here. The commit message is just useless blurps https://github.com/xiaoyifang/goldendict-ng/commit/9aa3c44d4eddea4ae5197fb974173e65f80e97a3
=> refactor: move "internalpayerbackend", which is not a backend, to src/audio

.github/workflows/Release-all.yml, CMakeLists.txt, cmake/Deps_Unix.cmake
Stop using the trick of linking goldendict to icu4c-i18n/uc to bring the related dylibs to the app bundle.
(For whatever reason, icudata is not copied.)
Instead, change the strategy into:
Find out the icu4c's dylibs then explicitly pass them to qt_deploy_runtime_dependencies (which pass the arguments to underlying `macdeplogyqt -executable="path_to_some_dylib"`)
Actually fix https://github.com/xiaoyifang/goldendict-ng/issues/1954
=> fix: manually deploy icu4c dylibs for macOS

src/common/utils.hh, src/pronounceengine.cc, src/pronounceengine.hh
close https://github.com/xiaoyifang/goldendict-ng/issues/1962
`gdau://` are written by GD itself, and the files are known to be audio files.
There were probably some bug reports related to this.
=> fix: local audio files without extension are not added to dictAudioMap

src/dict/stardict.cc
amend https://github.com/xiaoyifang/goldendict-ng/pull/398
=> fix: stardict format's description HTML display (.ifo file)

src/dict/aard.cc, src/dict/bgl.cc, src/dict/dictdfiles.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/gls.cc, src/dict/lsa.cc, src/dict/mdx.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/stardict.cc, src/dict/utils/dictfile.cc, src/dict/utils/dictfile.hh, src/dict/xdxf.cc, src/dict/zim.cc, src/dict/zipsounds.cc
They are useless even since the original GD.
Stop parsing this 2 char str for nothing.
Depends on https://github.com/xiaoyifang/goldendict-ng/pull/1965
=> clean: delete useless fopen style mode char* API from File::Index

src/dict/dictdfiles.cc, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/forvo.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/lingualibre.cc, src/dict/mdx.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/stardict.cc, src/dict/website.cc, src/dict/xdxf.cc, src/dict/zim.cc
`dictionaryName` has `protected` visibility.
https://github.com/xiaoyifang/goldendict-ng/blob/9c46e5c317b894c3aab9dfb6efd2dd38e94352c7/src/dict/dictionary.hh#L318
Classes that don't use it just carries an unused std::string.
=> clean: remove duplicated `getName` overrides

src/audio/audiooutput.cc, src/dict/aard.cc, src/dict/bgl.cc, src/dict/btreeidx.cc, src/dict/btreeidx.hh, src/dict/dictdfiles.cc, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/mdx.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/dict/zim.cc, src/ftshelpers.hh, src/fulltextsearch.cc, src/fulltextsearch.hh
* Delete 3 unused `QSemaphore` in `dsl.cc`
* Stop using module wide `<QtConcurrent>` header
=> clean: delete unused QSemaphore and do a header cleanup

src/dict/stardict.cc
Partially revert https://github.com/xiaoyifang/goldendict-ng/pull/1972 (Double-checked the change, this is the only place where execution order matters.)
fix https://github.com/xiaoyifang/goldendict-ng/issues/1979
=> fix startdict index file reading

src/dict/aard.cc, src/dict/bgl.cc, src/dict/dictdfiles.cc, src/dict/dictionary.hh, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/epwing.cc, src/dict/forvo.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/lingualibre.cc, src/dict/lsa.cc, src/dict/mdx.cc, src/dict/mediawiki.cc, src/dict/programs.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/sounddir.cc, src/dict/stardict.cc, src/dict/transliteration/transliteration.cc, src/dict/transliteration/transliteration.hh, src/dict/voiceengines.cc, src/dict/website.cc, src/dict/xdxf.cc, src/dict/zim.cc, src/dict/zipsounds.cc
Pure deletion.
It was never used because every dictionary format's Description is a bulk of text.
=> clean: delete  Dictionary::getProperties which is unused since the first commit of GD

src/article_maker.cc
Not a proper way to do that after qt6.8 due to [the new API](https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop), but it just works on 6.7 or older.
and I'm not sure whether the dark mode's switch should be considered into auto mode in other platforms.
=> feat: auto dark reader mode for Windows

src/ui/mainwindow.ui
This widget never even exists.
Looks like a placeholder before the current "Welcome" page.
Note the inconsistent parent-child relationship between generated code & the ui file. This probably runes into undefined corner case. (I hate ui file.)
=> clean: delete a non-existential "welcome tab" widget

src/config.cc
Inspired by https://github.com/xiaoyifang/goldendict-ng/issues/1738
mplayer project has passed its prime and pretty much replaced by mpv.
Let's change it to vlc (and necessary flags to make it no-gui and quit right after).
=> fix: replace default external audio player from `mplayer` to `vlc`

src/audio/README.md, src/audio/audioplayerfactory.cc, src/audio/internalplayerbackend.cc, src/audio/internalplayerbackend.hh, src/config.cc, src/config.hh, src/ui/preferences.cc
Slightly related to https://github.com/xiaoyifang/goldendict-ng/issues/1738
Because on Linux, qt multimedia can uses the `GStreamer` which uses libspeex and it is not broken.
We currently don't ship FFmpeg backend for Windows & macOS.
If #1738 is not fixable, we can also consider reinstate the FFmpeg backend and build FFmpeg by ourselves.
Changing default back is as simple as changing the order of `availableBackends()`
---
=> refactor: default to Qt Multimedia and delete default player shenanigans

src/hotkeywrapper.cc, src/hotkeywrapper.hh, src/macos/machotkeywrapper.mm, src/main.cc, src/unix/x11hotkeywrapper.cc
These stuffs serve no purpose except for Windows's `nativeEventFilter`.
AFAIK, it is also unnecessary for Windows too, because only one "wrapper" is ever needed. However, right now I don't have access to a Windows machine.
The introduction of `nativeEventFilter`, which was called as `winEventFilter`, in Original commit doesn't explain anything https://github.com/goldendict/goldendict/commit/0b8743547107653d80fc1eec90a96ab57fb1fd33#diff-55edcc575deee8d79439ced3ef499d0a7369bff2be1717395fd5fab7128f5db5R204
Tested on Linux.
=> clean: limit QHotkeyApplication::(un)registerWrapper to Windows only

src/common/iconv.cc, src/common/iconv.hh, src/dict/hunspell.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/1998
Issue caused by https://github.com/xiaoyifang/goldendict-ng/pull/1990 https://github.com/xiaoyifang/goldendict-ng/pull/1989
Two things I missed
* `u32string::size` returns number of `char32_t` instead of number of bytes.
* `libiconv` doesn't check the byte order of `UTF-32` string (UTF-32 only uses 21 bits out of 32 bits, so I always assume checking byte order of UTF-32 string is easy). Related source code https://git.savannah.gnu.org/gitweb/?p=libiconv.git;a=blob;f=lib/utf32.h;h=4c11a89906c47aa9e42bc9a575ee5e37fcfeb27a;hb=HEAD#l26
=> fix Hunspell regression related to encoding

src/dict/mdx.cc, src/scripts/gd-builtin.js
Fix issue caused by `defer` for external scripts.
https://github.com/xiaoyifang/goldendict-ng/blob/ad192634235a89c62fc07eb766cc180c1533b418/src/dict/mdx.cc#L978-L981
The `defer` will delay the execution of external script to a time between "Page loaded" and `DOMContentLoaded`.
I don't put much thought yet, but this will immediately fix https://github.com/xiaoyifang/goldendict-ng/issues/1984
Also don't want to use jQuery because it creates a barrier on approaching the HTML standard.
=> fix: <script> without src is not delayed like <script src="..." defer>

src/ui/articleview.cc, src/ui/articlewebpage.cc
The original purpose of `Utils::Url::addQueryItem` was for accommodating `Qt4x5` which were wrappers of Qt4 -> Qt5 API changes. 
This one is inefficient because the construction of `QUrlQuery` needs to parse the query part of the URL. Each call of this function reparse the string. 
The worst case scenario of the one in `articleview.cc` is reparsing the query string 8 times, and each time it gets slightly more expensive.
I am not motivated to replace all, so only the highly used ones are replaced.
=> opt: replace some inefficient uses of QUrlQuery

src/dict/mdx.cc, src/scripts/gd-builtin.js
gdonready is used to complemented with defer.
after wrapped with gdonready ,the global js variables/functions seems lost its global scope.
=> revert: defer+gdonready

src/common/folding.cc, src/common/globalregex.hh
=> fix: cjk expand character can not be searched

src/langcoder.cc, website/docs/manage_groups.md
A regression introduced when porting from `QRegex` to `QRegularExpression`.
I didn't put enough thought when porting this one.
* fix https://github.com/xiaoyifang/goldendict-ng/issues/2019
* require either non-alphabet delimiters or at the end or beginning of the name string.
* uses only the last match
* update documentation to clarify the exact extraction method.
For reference, this is the original one https://github.com/goldendict/goldendict/blob/8c5b26a3924f15fb215e2a8e1e96d87531bf5393/langcoder.cc#L325-L342
=> fix: regression in finding `{id}-{id}` lang pair from dict name

src/ui/mainwindow.cc, src/ui/mainwindow.hh
current situation: the translate line can adjust its font size according to the icon size .
=> opt: remove words zoom in(out) from the menu and keep the shortcut

src/dict/utils/indexedzip.cc
=> fix: crash in archlinux due to 0 uncompress size

src/ui/mainwindow.hh, src/ui/scanpopup.cc, src/ui/scanpopup.hh
add a new toolbar at the right side(default) , the toolbar will hold all the found dictionaries which will navigate to the target dictionary when clicked.
=> feat: add founded dictionaries bar in the scanpop dialog

src/dict/utils/indexedzip.cc, src/dict/utils/zipfile.cc
fix: #2034 
though not elegant ,but it can work.
=> fix: dsl zip can not read the stream file

website/docs/install.md
On plain installation of windows, goldendict-ng seems to need MSVC runtime.  Mentioning this in the doc would improve user experience. 
Errors:
1. The code execution cannot proceed because MSVCP140.dll was not found. reinstalling the program may fix this problem.
2. The code execution cannot proceed because VCRUNTIME140.dll was not found. reinstalling the program may fix this problem.
=> doc: windows runtime requirement

src/main.cc
Setting QT_ENABLE_HIGHDPI_SCALING to 1 might not work well in some cases. Instead of hard-coding it to 1, this commit checks if it is already set, and if it is empty or not set, then set it to 1. This allows overriding the QT_ENABLE_HIGHDPI_SCALING to 0 by respecting the system-wide setting of environment variables.
=> fix: respect the setting of QT_ENABLE_HIGHDPI_SCALING of the system

locale/crowdin.ts, src/config.cc, src/config.hh, src/main.cc, src/ui/preferences.cc, src/ui/preferences.ui
Original:
enable log ,will require add the parameter to the goldendict.ext as paramater ,such as `--log-to-file`
Current:
=> feat:add an option to enable log through the preference

.github/workflows/Release-all.yml, CMakeLists.txt, redist/io.github.xiaoyifang.goldendict_ng.metainfo.xml
redo https://github.com/xiaoyifang/goldendict-ng/issues/2094
Hopefully, you don't mind.
Another issue is that the flathub have a new linter for release info and I have to add it.
https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/pull/36#issuecomment-2612071935
=> new release version

redist/io.github.xiaoyifang.goldendict_ng.metainfo.xml
😅 f
https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/pull/37
=> reverse order of <release> in metainfo.xml for flathub's linter

redist/io.github.xiaoyifang.goldendict_ng.metainfo.xml
Reverts xiaoyifang/goldendict-ng#2104
:)
https://github.com/ximion/appstream/blob/93c0af6df69e319cfb60f855f4e47472b42dac6b/src/as-validator-issue-tag.h#L905-L910
https://github.com/flathub/io.github.xiaoyifang.goldendict_ng/pull/37
=> Revert "reverse order of <release> in metainfo.xml for flathub's linter"

src/main.cc
1. use same translations loading mechanism (QLocale based QTranslator::load as suggested by https://github.com/xiaoyifang/goldendict-ng/issues/530#issuecomment-1519775951)
2. only load Qt ts file when gd's ts file loading success
My lang_region combo is `zh-Hans-CA`
Before:
Qt loading `zh_CN` success and GD's locale failed -> inconsistency -> macOS's system menu translated and GD's menu not translated
Reason: The QLocale's string constructor may or may not have bug. If it doesn't have bug, then we uses it wrong, and something got lost as `zh-Hans-CA` becomes `zh-Hans-CN`. https://github.com/xiaoyifang/goldendict-ng/pull/2119#issuecomment-2630811073
After:
As `zh-Hans-CA` shouldn't match anything. All 3 failed.
=> fix: interface languages inconsistency caused by corner cases of translation files loading

src/audio/multimediaaudioplayer.cc, src/audio/multimediaaudioplayer.hh
QPointer.clear will not delete, like unique_ptr. So just make the QBuffer in the stack.
=> fix: multimedia memleak

.editorconfig, .git-blame-ignore-revs, src/article_maker.cc, src/common/utils.hh, src/dict/bgl.cc, src/dict/btreeidx.cc, src/dict/dictdfiles.cc, src/dict/dictionary.cc, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/loaddictionaries.cc, src/dict/mdictparser.cc, src/dict/mdx.cc, src/dict/mediawiki.cc, src/dict/programs.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/website.cc, src/dict/xdxf.cc, src/dict/zipsounds.cc, src/dictionary_group.cc, src/instances.cc, src/ui/articleview.cc, src/ui/edit_groups_widgets.cc, src/ui/edit_sources_models.cc, src/ui/mainwindow.cc, src/ui/scanpopup.cc
Seems to be a legacy of Qt4, where size type is `int`.
https://doc.qt.io/archives/qt-4.8/qvector.html#size
And also pre C++11 size_type was unsigned (?).
Only warnings in function body is changed (use `auto` as much as possible) in this PR. There are a few in function return & calling positions.
=> clean: reduce implicit `int` -> `(q)sizetype` conversion warnings

.clang-tidy, src/ui/edit_sources_models.cc, src/ui/edit_sources_models.hh
- delete boilerplates (`parent` which is useless for 2 dimension data & `index` which can just have a fix implementation for 2 dimension data)
- add `override` when overriding
The primary feature of `QAbstractTableModel` is implementing things that isn't needed by a table-like data, which is what we use.
=> clean: replace QAbstractItemModel with more suitable QAbstractTableModel

src/ui/edit_sources_models.cc
https://doc.qt.io/qt-6/qitemeditorfactory.html#registerEditor
The original GD is leaking memory here.
However, it is fixed by https://github.com/xiaoyifang/goldendict-ng/commit/16f853b68b5c648fd42baeeb35158162539079a6#diff-b04fa5c862334cf34d4f59188ab1bd597387ece9a46b3149fea381bcd42ec195R299
=> clean: rm oudated TODO about QItemEditorFactory::registerEditor's lifetime

.gitignore, CMakeLists.txt, cmake/Package_Linux.cmake, resources.qrc, src/build_config.hh.in, src/config.cc, src/ui/mainwindow.cc, src/version.cc, src/version.hh
It's pretty standard.
- autoconf -> https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/html_node/Configuration-Headers.html
- meson -> https://mesonbuild.com/Configuration.html
The alternative is looking these data from `build.ninja`.
=> refactor: use configure_file for build time string data

redist/mac_info_plist_template_cmake.plist, src/macos/gd_clipboard.hh, src/macos/mac_url_handler.cc, src/macos/mac_url_handler.hh, src/main.cc, website/docs/topic_anki.md
demo
https://github.com/user-attachments/assets/6f285104-7728-4876-9226-dfa8b5fee33f
- close https://github.com/xiaoyifang/goldendict-ng/issues/1867
- related https://github.com/xiaoyifang/goldendict-ng/pull/227
=> feat: implement `goldendict:://{world}` URL handler for macOS

src/macos/mac_url_handler.cc
amend https://github.com/xiaoyifang/goldendict-ng/pull/2133
macOS is more uniformed. Globally, the URL will be converted to punnycode / ACE code.
Tested with Safari, so I assume it works everywhere.
=> handle ACE / punnycode in macOS url handler too

.gitignore, CMakeLists.txt, cmake/Package_Linux.cmake, resources.qrc, src/build_config.hh.in, src/config.cc, src/ui/mainwindow.cc, src/version.cc, src/version.hh
Revert
- https://github.com/xiaoyifang/goldendict-ng/pull/2132
- https://github.com/xiaoyifang/goldendict-ng/pull/2135
The version.txt file is bundled into the executable at linking time (? or similar).
configure_file causes rebuild every time cmake rerun.
For AUR / gentoo / (other places where user constantly pull new verions), this file needs to regenerate constantly.
=> revert "refactor: use configure_file for build time string data"

src/dict/xdxf.cc
follow up of https://github.com/xiaoyifang/goldendict-ng/pull/2139
Allow xdxf to use the same name as the main dict name, like other formats.
=> opt: lift the useless special case of xdxf's icon name

CMakeLists.txt, src/dict/lingualibre.cc, src/dict/stardict.cc, src/dict/transliteration/custom.cc, src/fulltextsearch.cc, src/iframeschemehandler.cc, src/texttospeechsource.cc, src/tiff.cc, src/tiff.hh, src/ui/about.cc, src/ui/dictheadwords.cc, src/ui/edit_dictionaries.cc, src/ui/favoritespanewidget.cc, src/ui/historypanewidget.cc, src/ui/mainwindow.cc, src/ui/preferences.cc, src/ui/translatebox.cc
Enable this https://doc.qt.io/qt-6/qtglobal.html#QT_ENABLE_STRICT_MODE_UP_TO
For 6.8.2 is because this commit https://github.com/qt/qtbase/commit/f9163ae7a8167daded0798654d99a2e3a5aaa2b5 . 
The `QT_NO_CAST_FROM_ASCII` is too much to fix.
Changes and problems that could have been prevented:
- Java-style iterators for Qt containers 
- 🤮🤮 We have a few
- foreach macro https://doc.qt.io/qt-6/foreach-keyword.html#the-foreach-keyword
- 🤮🤮 a few in TTS
- https://github.com/qt/qtbase/blob/6dc0e593939cbeaeb45392d8daf7fcd90e8cb0f8/src/corelib/global/qforeach.h#L42-L44
- QUrl implicit conversions from QString
- This bug https://github.com/xiaoyifang/goldendict-ng/pull/1425
- Allowing narrowing conversions in signal-slot connections (see QT_NO_NARROWING_CONVERSIONS_IN_CONNECT)
- Pretty sure we fixed …
=> clean: enable `QT_ENABLE_STRICT_MODE_UP_TO` for Qt6.8.2+

src/dict/dictserver.cc, src/dict/hunspell.cc, src/dict/programs.cc, src/dict/stardict.cc, src/dict/xdxf.cc, src/ftshelpers.cc, src/headwordsmodel.cc, src/history.cc, src/langcoder.cc, src/speechclient.hh, src/texttospeechsource.cc, src/ui/dictheadwords.cc, src/ui/dictionarybar.cc, src/ui/favoritespanewidget.cc, src/ui/historypanewidget.cc, src/ui/preferences.cc
close https://github.com/xiaoyifang/goldendict-ng/issues/2144
We can probably add a new auto format step to enforce various Clazy auto fixes later. (or not, there should be no barrier on new incoming PRs from new persons.)
The performance impact?
miniscule 😅
=> opt: properly use Qt containers in range for loops with std::as_const

src/article_maker.cc, src/common/utils.hh, src/dict/bgl.cc, src/dict/btreeidx.cc, src/dict/dictdfiles.cc, src/dict/dictionary.cc, src/dict/dictserver.cc, src/dict/dsl.cc, src/dict/gls.cc, src/dict/hunspell.cc, src/dict/loaddictionaries.cc, src/dict/mdictparser.cc, src/dict/mdx.cc, src/dict/mediawiki.cc, src/dict/programs.cc, src/dict/sdict.cc, src/dict/slob.cc, src/dict/stardict.cc, src/dict/website.cc, src/dict/xdxf.cc, src/dict/zipsounds.cc, src/dictionary_group.cc, src/instances.cc, src/ui/articleview.cc, src/ui/edit_groups_widgets.cc, src/ui/edit_sources_models.cc, src/ui/mainwindow.cc, src/ui/scanpopup.cc
Revert https://github.com/xiaoyifang/goldendict-ng/pull/2127
potentially related 
- https://github.com/xiaoyifang/goldendict-ng/issues/2113
- https://github.com/xiaoyifang/goldendict-ng/issues/2152
Still not sure what's wrong, code looks correct.
But let's revert this fast, before it causes more errors.
=> fix: revert "clean: reduce implicit `int` -> `(q)sizetype` conversion warnings (#2127)"

src/dict/stardict.cc
fix the following warning
```
Warning: 02-14 15:56:07 Stardict: non-alpha entry type 0xa for the word 嗣 encountered in "Chin-Eng-Buddhist
```
=> fix:newline character contained in the string

src/dict/dictionary.hh, src/dict/mdx.cc
there is no need to pass parent to the QObject.
After pass parent to QObject, it will also be managed by QObject .
which will lead to double-release the memory.
=> opt: DataRequest was managed by shared_ptr

website/docs/topic_userstyle.md
Related
- https://github.com/xiaoyifang/goldendict-ng/issues/2102
I find it is not proper and potentially misleading.
Problem:
In GD we make the webpage's header like
```html
<script>
DarkReader.enable({})
</script>
Then, in user's article-script.js file, a second
DarkReader.enable({})
what could happen here ? This is either undefined or not well tested by upstream.
```
Though, in user's `article-script.js`, they can `disable` first, but that will causes a "flash" from a dark theme to a slightly different dark theme.
The proper way is provide someway to modify the first `DarkReader.enable({})`
=> delete doc about darkreader.js customization

icons/README.txt, icons/folder_active.svg, locale/crowdin.ts, resources.qrc, src/common/globalbroadcaster.hh, src/ui/favoritespanewidget.cc, src/ui/favoritespanewidget.hh, src/ui/mainwindow.cc, src/ui/mainwindow.hh, src/ui/scanpopup.cc, src/ui/scanpopup.hh, website/docs/manage_groups.md, website/docs/ui_favorites.md
Implement https://github.com/xiaoyifang/goldendict-ng/pull/2178#issuecomment-2675986213
---
Breakage / Enhancement:
Original GD's folder is ambiguous, group->folder mapping only maps the name.
```perl
a & b->a are considered the same.
|
| -> a
| -> b -> a
|    | -> c
```
Now requires the path fully specified like `b/a` for b->a folder and `a` is for folder a that is directly under top level only.
The group->folder is now only used when switching groups. Switching to a new group -> auto active folder of chosen.
---
Coding:
The central data is just a QStringList hat represents the nested folder.
Then various accompanying methods to utilize it.
---
Main idea: the 🌟  now associated with **the active folder <img width="24" src="https://github.com/user-attachments/assets/4c0f39ff-f85e-43ff-8c5f- …
=> feat: revise Favorites by introducing active folder to reduce ambiguity

.github/workflows/deploy_website.yml
GitHub disabled `actions/cache@v2` https://github.com/xiaoyifang/goldendict-ng/actions/runs/13655528741
But we don't use it at all, caching is only used by some plugins. Our website is also very small.
https://squidfunk.github.io/mkdocs-material/plugins/requirements/caching/
=> bump versions in deploy_website.yml

src/main.cc
Should fix https://github.com/xiaoyifang/goldendict-ng/issues/2247
Change GD's translator loading from QLocale based method only to
1. try the filename based method if interfaceLanguage is present
2. try the QLocale based method if interfaceLanguage is emptry
The 2. sometimes doesn't work because of https://github.com/xiaoyifang/goldendict-ng/issues/2120
Root issue: `QTranslator` & `QLocale` have tricky behaviors. Note that the 3 major operating systems do the Locale thing slightly differently.
Previous:
- https://github.com/xiaoyifang/goldendict-ng/pull/2119 
- That PR switched gd_ts to QLocale so that when interfaceLanguage is empty, uses system's QLocale.
- This PR reverted it partially because exactly what will the constructed QLocale do is tricky.
- …
=> fix: corner cases of translation loading by attempting filename based gd_ts loading first

src/main.cc
Extra ensurance for https://github.com/xiaoyifang/goldendict-ng/issues/2247
Still wrong in corner cases due to
- https://github.com/xiaoyifang/goldendict-ng/issues/2120
But in chinese & russian, it is correct. So let's assume it works for pretty much everyone.
=> ensure qt & webengine ts files loaded are consistent with GD

src/ui/dictionarybar.cc, src/ui/dictionarybar.hh, website/docs/ui_toolbar.md, website/mkdocs.yml
Ctrl/Shift+Click a dict -> Enter Mode; Select one and only one dict.
Normal Click -> Change the one and only selection to another.
Ctrl/Shift+Click the not selected one -> identical to Normal Click (Undocumented, if user noticed then they noticed, if not, doesn't matter.).
Ctrl/Shift+Click the selected one -> Exit the mode, restore selection based on Ctrl/Shift
- This is no need for indicator because user may clicking around and notice that only a single one is selectable without the risk of losing previously selected. 
- The thing can be explained by 1 sentence because there is no functionality overloading and there is real change when in this mode. 
fix #2213
=> feat: rework "solo" "mode" to Single Selection Mode

src/audio/audiooutput.cc, src/dict/dictserver.cc, src/dict/forvo.cc, src/dict/lingualibre.cc, src/dict/mediawiki.cc, src/dict/website.cc
Details of the errors encountered are listed in [the issue](https://github.com/xiaoyifang/goldendict-ng/issues/2272) mentioned in PR's title.
This just adds an include of QDebug to one file, and moves the includes of AUTOMOC generated headers to the very last line of five files that contain such includes.
=> Fixes issue #2272, minor changes fixing compilation against Qt 6.9.0

locale/crowdin.ts, src/ui/dictionarybar.cc, src/ui/dictionarybar.hh, website/docs/ui_toolbar.md
https://github.com/xiaoyifang/goldendict-ng/issues/2213
Major Difference: No "Mode" anymore.
Select a single dict.
If a dict is selected and is the only one left, then reselect all.
This retains all the previous features except restoration.
Shift+Click -> Capture the current selection, and add a right click menu item "restore selection".
This is better than all previous designs because 
1. there is no mode anymore.
2. capturing could happen in anytime a user want to
3. restoration will never will be lost unless capturing again or after restoration
The composition of those two features covers all previously mentioned needs.
Doc is much simpler, there is no need for a cases table anymore.
+ Restore now needs two click (Not a flaw, because modifier + clicking requires a "mode" to know when …
=> feat: split Single/Solo Selection Mode to 2 composable features

src/scripts/gd-builtin.js
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/event
[use const variable instead](https://github.com/xiaoyifang/goldendict-ng/pull/2312/commits/e91fb27854022c1eda04089b6d20cbffba5754f2)
=> opt:remove deprecated window.event variable

src/wordfinder.cc, src/wordfinder.hh
`allWordWritings` is accessed by multi-threads ,and it has no protection against race contention.
using Copy-On-Read strategy to protect the variable by private method(which has mutex guard).  method `updateResult`&`startSearch` will only use its copy.
maybe has some connection with https://github.com/xiaoyifang/goldendict-ng/issues/2113 .
=> opt:protect vector variable in wordfinder with copy-on-read

src/main.cc
`disable-web-security`  should have not taken effect for a while .
can be removed.
=> opt:remove the not used parameter

src/main.cc, src/ui/mainwindow.cc
This is a small PR.
It does two things which mainly concern correctness on Linux Wayland platform:
1. It calls `setDesktopFileName` (available since Qt 5.7) so that app_id under Wayland is set to a value which allows compositors and other applications to find the `.desktop` file supplied and through that the correct application icon.
2. It corrects the argument to `setOrganizationDomain` to a value which is conceptually sound (the actual domain name, distinct from a URL) and does not get mangled on processing due to containing backslashes.
=>  Update main.cc to ensure correctly setting Wayland app_id

.github/workflows/PR-check-cmake.yml, src/audio/ffmpegaudio.cc
Those code works since at least FFmpeg 5 (I tested with FFmpeg@5 from homebrew. They may work even earlier, but we don't care).
There will be no warnings in Ubuntu build now. Enable warnings_as_error for it too.
=> delete FFmpeg version < 7 conditionally compiled code

src/audio/audiooutput.cc, src/audio/ffmpegaudio.cc
Fix this crash with no obvious back trace. No idea exactly what's wrong.
To reproduce: clicking insanely fast.
Combination is Qt6.9.1 + FFmpeg@5 + M1 macOS.
---
Random thought:
We rarely need `deleteLater()` because most of the objects are small and deleting is cheap. Keeping objects slightly longer only causes problems.
---
https://doc.qt.io/qt-6/qobject.html#dtor.QObject
> Deleting a [QObject](https://doc.qt.io/qt-6/qobject.html) while it is handling an event delivered to it can cause a crash. You must not delete the [QObject](https://doc.qt.io/qt-6/qobject.html) directly if it exists in a different thread than the one currently executing. Use [deleteLater](https://doc.qt.io/qt-6/qobject.html#deleteLater)() instead, which will cause the event loop to delete the object after all pending …
=> fix: ffmpeg backend crash when clicking play audio too fast

src/audio/ffmpeg_audiooutput.cc, src/audio/ffmpeg_audiooutput.hh, src/audio/ffmpegaudio.cc, src/audio/ffmpegaudio.hh
1. remove `Q_D` macro, which is completely useless for end-user application developers.
2. remove insane naming of AudioOuptout inside AudioOutputPrivate inside AudioOutput
3. merge duplicated stop()
4. minor style fixes
=> remove useless complexity from FFmpeg -> AudioOutput

cmake/Deps_Linux.cmake, src/hotkeywrapper.cc, src/hotkeywrapper.hh
There are only 4 methods (Constructor, SetHotKey, UnRegister, Signal->Activated) that should be public.
Everything else is platform implementation details.
Reorder code so that things for each platform together can be found together.
=> reorder and document hotkeywrapper

src/ui/scanpopup.cc
close: https://github.com/xiaoyifang/goldendict-ng/issues/2409
The `dictionaryBar.setDictionaries` internally uses `mutedDictionaries` which is a pointer.
There are many codes in `DictionaryBar.cc` checking null of `mutedDictionaries` but all of them are useless, because those pointers can totally point to invalid states.
For the record, I don't like the crash, this fix, the related code. None of them are reliable.
=> fix: update mutedDictioanries for dictionaryBar first, or it will crash

src/ui/mainwindow.cc
Credit: found by CLion.
This code assign a QString and never uses it.
=> delete minor dead code in MainWindow::addAllTabsToFavorites

.github/workflows/Manual-Build-Action.yml, .github/workflows/PR-check-cmake.yml, .github/workflows/Release-all.yml, .github/workflows/Sonar Cloud.yml, .github/workflows/create-vcpkg-export-archive.yml, .github/workflows/issue-translator.yml
Potential fix for [https://github.com/xiaoyifang/goldendict-ng/security/code-scanning/20](https://github.com/xiaoyifang/goldendict-ng/security/code-scanning/20)
To fix this problem, you should add a `permissions:` block at the top-level of the workflow file (.github/workflows/PR-check-cmake.yml), immediately beneath the `name:` declaration and before the `concurrency:` and `on:` sections. This permissions block should specify the least privilege required for the workflow, which in this case is `contents: read`. This setting will apply to all jobs in the workflow unless they have their own, more permissive `permissions` block. The `permissions:` declaration must be YAML-compliant, and because none of the current jobs write to the repository, raise issues, or modify pull requests, there is …
=> Potential fix for code scanning alert no. 20: Workflow does not contain permissions

website/docs/architecture.md, website/docs/developer.md, website/docs/howto/how to customize the opencc.md, website/docs/howto/how to manually reindex dictionary.md, website/docs/howto/how to use breadpad crash analysis.md, website/docs/manage_sources.md, website/docs/topic_anki.md, website/docs/topic_move_index_folder.md, website/docs/topic_website_scripting.md
- Fix grammar errors, spelling mistakes, and inconsistent formatting in multiple documents
- Standardize list item formatting and punctuation usage across documentation
- Optimize expression clarity of certain sentences
=> docs: Fix grammar errors and standardize format in documentation

.github/workflows/Release-all.yml
macos 13 dependecies installation takes too much time. > 40mins
=> action:remove macos 13

src/dict/stardict.cc
Use QTextStream instead of direct QFile reading, supporting automatic Unicode detection Convert QByteArrayView to QStringView for text processing, ensuring correct UTF-8 encoding parsing
=> refactor(dict): Improve encoding handling for StarDict IFO file parsing
